oxen-io/session-desktop

libloki/libloki-protocol.js, libtextsecure/message_receiver.js
If an incoming friend request message can't be decrypted, just ignore the message instead of displaying every failed decrypted message in a new conversation (not spam friendly!)
Possible reasons for failing to decrypt:
- it's spam
- the emitter didn't encrypt properly: different algo used, wrong iv shared, etc.
- the message was intended for someone else
=> Ignore friend request messages that couldn't be decrypted

js/modules/migrations/migrations_0_database_with_attachment_data.js, js/signal_protocol_store.js, libloki/libloki-protocol.js, libtextsecure/account_manager.js, libtextsecure/outgoing_message.js, protos/SignalService.proto
- user's prekeys now are generated for a specific recipient (skip generation of 100's of prekey upon registration)
- signatures of signed keys are now stored in the database
- a prekey bundle is attached to the message under any of the following conditions:
- there are no prekeys for the recipient (fallback mode)
- the key exchange is not completed (e.g. the recipient has not sent a Signal message yet)
This is a first pass, as the logic will most probably evolve (blocking friend request)
=> Prekeys sending: first pass

libtextsecure/outgoing_message.js, libtextsecure/sendmessage.js
This is a simple change to have a default 4 day ttl for friend request messages
If no ttl is supplied to transmitMessage the default value will be 24 hours
Eventually the ttl will need to be able to be manually set by the user which could change the location of this logic (possibly just getting attached to this.ttl similar to timestamp etc?)
Also changed to simply grab the first outgoing object, in the future will either need to modify to work with multiple devices or simply refactor everything to not use device ids
The target calculation in proof-of-work.js lowers the target value as the ttl raises, the rate at which this happens will likely need to be fine tuned later down the track when we have more information about how much load in the network needs to be mitigated etc
=> Friend req ttl

js/modules/migrations/migrations_0_database_with_attachment_data.js, js/signal_protocol_store.js, libloki/libloki-protocol.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js
First pass of handling incoming friend requests:
- decode prekeyBundleMessage (handlePreKeyBundleMessage)
- then store prekeys in db (savePreKeyBundleForNumber ) if not existing yet (lookup for a pubkey - keyId pair: loadContactPreKeys and loadContactSignedPreKeys)
- add a function to send an empty reply (sendEmptyMessageWithPreKeys) Not used yet.
- a couple of fixes for the previous PR
=> Handle incoming friend request 

_locales/en/messages.json, background.html, js/models/conversations.js, js/views/conversation_view.js, libtextsecure/outgoing_message.js, stylesheets/_conversation.scss
This is a first implementation of the friend request lock, sender side (i.e. it does not yet check whether the friend request has been accepted).
Basically, this allows the user to send one message (the friend request message) then it locks the text editor until the timer expires (or onFriendRequestApproved is called)
This PR also changes the placeholder text in the editor, to display whether
1. the user is typing a friend request message
2. the editor is locked because we're waiting for a friend request approval
3. the user can just send messages at will
=> Lock input friend request

config/development-1.json, main.js, package.json
This PR adds `yarn start-multi` command for easier launch.
Rather than setting `NODE_ENV`, we can instead set `NODE_APP_INSTANCE`.
This also fixes the problem where you can create multiple instances when using `production` environment.
=> Clean up multi instance code.

libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js
Initially commented out for debugging/development.
Now that we are getting things working, we want to restore padding.
The idea is keep the Signal crypto properties as pristine as possible.
=> restore ciphertext padding

app/sql.js
Currently, `addOrReplaceContact...` doesn't replace when providing an existing pair of (`keyIdentityString`, `keyId`), it just adds a new row.
This is because in SQL, `INSERT OR REPLACE INTO` works with unique indexes.
Tested by calling `window.textsecure.storage.protocol.storeContactPreKey` with various arguments, and verified that the values were updated when providing existing keyIdentityString,keyId.
=> create unique index for contact prekeys (to allow using REPLACE)

js/logging.js, js/modules/loki_message_api.js, libtextsecure/message_receiver.js
I noticed `log.warn` and `log.error` actually uses `console.log` under the hood.
This makes it all very difficult to filter the console by log level as well as spot actual warnings and errors.
This PR basically makes `log.xxx` actually use `console.xxx` when in development mode.
Production builds are left untouched as it is a best practice in the industry.
Additionally, this PR makes some logs use `log.debug` to filter out unimportant logs like HTTP polling, "empty"  events, etc.
BEFORE
AFTER
=> Use correct log level in development mode

_locales/en/messages.json, js/background.js, js/models/conversations.js, js/models/messages.js, js/views/app_view.js, js/views/conversation_view.js, libloki/proof-of-work.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, protos/SignalService.proto, ts/components/conversation/FriendRequest.tsx
This PR fixes the logic issues with the previously implemented friend request.
I also refactored some things and moved the logic of adding friend requests out into `message_receiver` and `background`
The new logic is the following:
`isFriend = Whether we are friends`
`isKeyExchanged = No cipher text received`
- If not `isFriend` then use fallback encryption.
- This sets the message type to `FRIEND_REQUEST`.
- For every message sent, if not `isKeyExchanged` then we attach `preKeyBundle` to the `Envelope`.
- `preKeyBundle` used to be inside the `Envelope` content but was moved outside of it.
- `preKeyBundle` is always encrypted using the fallback encryption.
- If we get an encrypted message from the other user then set `isKeyExchanged` to `true`.
=> Friend request fixes

js/views/conversation_view.js
I was getting errors after refreshing the app with an existing conversation.
Basically `onChangePlaceholder` is triggered once before the `initialize` function has the chance to assign `this.$messageField`. Then it's triggered again twice, so I thought simply guarding `onChangePlaceholder` might be easier than changing the order in which stuff happens in `initialize`.
Thoughts?
=> Fix accessing $messageField before assignment

libtextsecure/outgoing_message.js
`getKeysForNumber` does not return a boolean consistently.
When the keys are actually present, but the device is marked as stale (e.g. there is no valid session yet) then the value returned is something like `[undefined, true]` (i.e. the return values of some functions). 
This PR simply merges the boolean values into one and makes sure that `true` is returned when everything goes according to plan.
=> Fix getKeysForNumber when staleDevices is not empty

js/models/conversations.js, js/views/conversation_view.js, libloki/libloki-protocol.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, protos/SignalService.proto
Moved the prekeybundle back to a content message
Since Signal protocol handles session initiation after one party has the other's prekeys, we only need to send prekeys for the initial friend request
This allows for simplifications of some of the friend request logic
TODO:
1. Decouple the state of the UI w/r/t conversation and messages
2. Trigger friend request accepted event on any message that arrives in the pending state, not just empty message
=> Big refactor, prekeybundle moved back to a content message

app/sql.js
Tiny PR to support the following "session reset" reviews.
Basically, we want to ensure that the contact's prekeys we use are always the latest (highest keyId) available in the database.
=> Ensure the contact prekey returned is always the latest available

js/models/conversations.js
(For posterity)
I noticed a glitch in the rendering of the last message shown in the conversation list, upon sending a new message.
Basically, the issue was simply ordering since we need to save the new message to database first before we update some timestamps on conversation, which triggers to fetch the last message from the database.
=> Fix glitch in last message shown in conversation list

.gitlab-ci.yml
Setting up gitlab-ci.yml to get our tests running for commits and pull-requests to loki-project/loki-messenger.
In the future we'll need to extend this file to actually build our binaries for production.
=> set up gitlab tests

background.html, js/loki_protocol_store.js, js/models/conversations.js, js/signal_protocol_store.js, libloki/libloki-protocol.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js
More consistent naming of key storage functions, moved some loki messenger only functions into new file
Made getPreKeyBundleForContact return object rather than a proto to be consistent with other functions
=> Clean up function names and loki store

test/index.html
The build randomly fail for the 'SecretSessionCipher' tests, so let's take this one out for now (we don't use SecretSessionCipher at this stage I believe, as it seems to be related to the "sealed sender" functionality.
=> remove secretsessioncipher test

.gitignore, Gruntfile.js, bower.json, components/JSBI/dist/jsbi.mjs, js/modules/loki_message_api.js, js/modules/util_worker_interface.js, js/util_worker_tasks.js, libloki/proof-of-work.js, libloki/test/index.html, libloki/test/proof-of-work_test.js, libtextsecure/message_receiver.js, package.json, preload.js, test/index.html, yarn.lock
Rip the worker logic out of message_receiver into own file and add the functionality for it to work with pow.
Have added jsbi.mjs which is the the minified Google implementation of big integers and concat it to the util_worker the same way that it was done for bytebuffer.
This is because the webworkers are not running in the node environment so we do not have access to 'require'. It was already kind of weird requiring the bytebuffer module when we already had the whole module included in the window.
This change makes it much easier to add functionality that the utilWorker is able to do and also spin up more worker threads in the future if we want.
Fix pow tests to work with those changes.
TODO: Production PoW calculation still seems unreasonably high. It was based off the bitmessage …
=> Refactor PoW calculation to use webworkers

.gitlab-ci.yml
binaries are build under `/dist` by default.
Latest merge from upstream/textsecure changed the test to look under /release.
=> set build dir to /release on win to align with other platforms

js/util_worker_tasks.js, libloki/proof-of-work.js, libloki/test/metrics.js, metrics.html, metrics_app.js, package.json
As PoW might become a recurrent issue (too long - not long enough - too dependent on the computer) it might be nice to gather and display some data locally:
run `yarn pow-metrics` and go to `http://localhost:9000/metrics.html` to see the dashboard (fancy name *cough* *cough*).
You can customise the different settings for each test.
The idea is to isolate the influence of one parameter at a time, by keeping everything else constant.
I made some changes to the pow logic:
- ability to specify a nounceTrials, an nonce increment and start value (for multi-workers)
- ability to increment a uint8array by any integer, not just by 1.
- actually calculate the hash for the initial value of the nonce (we were incrementing the nonce before actually trying anything)
=> PoW statistical measurements

.travis.yml
resolves #118.
We won't be able to see the travis output until the job has been completed with this change.
=> Added travis_wait on windows.

app/sql.js, config/default.json, js/conversation_controller.js, js/models/conversations.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_snode_api.js, libloki/service_nodes.js, libloki/test/service_nodes_test.js, libtextsecure/http-resources.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, main.js, preload.js
Random.snode is now used to query the network for lists of nodes in the swarm for a specific contact
Sending a retrieving messages now fires off multiple queries to the nodes in these lists and some rudimentary organising of this is in place
Some thinking still needs to be done about how to handle the outcome of all these requests
E.g.
- What should be the minimum successful responses we want when sending a message? (A % of the max # of nodes we have had in list? Hardcoded to 3?
- What should we do if we run out of nodes to try and have received a nonzero # of successful responses that is less than this minimum threshold? (Just approve? (invalidates the idea of threshold) Throw error? (Realistically the request was a success) Small warning? (User shouldn't really need to see))
- How …
=> Swarm requests

js/models/conversations.js, libloki/api.js, libtextsecure/message_receiver.js
Fixes #145 
Basically in libloki/api.js we want to use `textsecure.messaging.sendMessageToNumber` which is a higher-level function that attaches the profile to the message proto.
Then when receiving messages, we allow having a `DataMessage` even for friend request messages.
To do so, we need to bail early if the message body is falsey.
(The linter has changes some indentation in message_receiver.js so best ignore whitespace changes in github: Diff settings => Hide whitespace changes)
=> Send profile along with friend request accept message

js/conversation_controller.js, js/models/messages.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_snode_api.js, libtextsecure/errors.js, libtextsecure/outgoing_message.js
More robust handling of swarm requests and how failures and edge cases are handled
Now don't just wait for a single successful send message request but continue trying until we run out of nodes or we get enough responses, the same way we do retrieving messages
Added a failure threshold for the nodes we are querying so we aren't deleting them from memory until they have failed 3 times
Make sure we don't just make 3 successful queries to the same node 3 times
Added some more specific errors for the different ways sending a message can fail
Feel like this logic is getting a bit messy, especially the stuff for sending and receiving messages seems mostly duplicated with only a few differences, not really sure how to go about simplifying/generalising it
Also feel like the responsibilities of …
=> Swarm error handling

Gruntfile.js, app/sql.js, config/default.json, config/development-1.json, js/conversation_controller.js, js/models/conversations.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_p2p_api.js, js/modules/loki_snode_api.js, libloki/api.js, libloki/friends.js, libloki/local_loki_server.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, main.js, preload.js, protos/SignalService.proto, test/index.html
Start of P2P stuff, added a new message proto type for a loki address message
When you launch the app you "broadcast" a message to all of your friends with your P2P address info (currently just dummy data because we don't have a way to get our loki address yet) and then the recipient stores this in memory
Next up is the logic for pinging, i.e. the timers etc and then hooking in the message sending to use these addresses if the other user is "online"
Also allowing the user to manually select the port they want to use for their http server (and fall back to the node port finding thing if it doesn't work)
Fixes #154
=> Loki address broadcast

js/models/conversations.js, js/modules/loki_message_api.js, js/modules/loki_p2p_api.js, libloki/api.js, libtextsecure/http-resources.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js
Lots of logic for establishing a p2p connection, managing when the other user is online vs offline etc. Will always try to use P2P messaging when it can and fall back to storage server otherwise
Pinging system to determine whether a user is online or offline, staggered so one user always pings the other until one of them goes offline
Failing to send a P2P message will result in a contact being marked as offline
Next up is the UI for online/offline contacts (Mik)
I feel like there might be some redundant logic in here somewhere (as in I think I am doing more back and forth than totally necessary but can't wrap my head around it yet)
I have tested this over lokinet (hardcoded .loki address) and it works like a charm ;)
Once the localhost.loki is working (and they fix it for Macs) then we …
=> P2P messaging

_locales/en/messages.json, background.html, js/background.js, js/link_previews_helper.js, js/models/messages.js, js/modules/signal.js, js/modules/types/attachment.js, js/settings_start.js, js/views/settings_view.js, libtextsecure/sendmessage.js, main.js, preload.js, settings.html, settings_preload.js
This PR expands on the Signal preview functionality to make it work with our application.
Resolves #179
Resolves #180 
I ripped some code out into a custom `helper` class, but left the original code untouched (in `conversation_view`)
We save the images locally inside the `attachments` folder and under `previews`
**Changes:**
- Disable sending attachments in messages
- Added local link preview setting
- Added showing link previews of incoming messages
=> Added local link previews

js/conversation_controller.js, js/models/conversations.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_snode_api.js, preload.js
Fixed a nasty 'returning a reference' bug I introduced a while back which made us check for new swarm nodes before sending every message
Found another couple dumb things left around from the transition from using sets for swarm nodes to using arrays
Also found a nice little infinite loop bug that I had bumped into a couple times from using `completedNodes.length` instead of `successfulNodes`
Overall slightly less disgusted by all this swarm stuff
=> Swarm fixes

.gitattributes
This change was made to fix travis a while ago breaking from changing line endings, but we have some signal upstream files with combined line endings which get all sorts of messed up when they are modified.
Hopefully travis will be happy with this instead
=> Stop git from defaulting to changing line endings

config/default.json, js/modules/loki_snode_api.js, libloki/api.js, libloki/local_loki_server.js, libtextsecure/message_receiver.js, main.js, preload.js
Use the newly added localhost.loki lookup to get our .loki address to send to our contacts for P2P messaging
Also do a reverse lookup on this .loki address to get the private ip our hidden service is using so we can bind our P2P server to it, this allows us to receive messages P2P without having to forward ports
=> Localhost loki

js/modules/loki_message_api.js
Implements #197.
This PR requires the mirror changes in the storage server before merging.
TODO: With these changes, the similitude between `retrieveMessages` and `sendMessage` is now increased and would make them good candidates for refactoring.
=> Use new message json rpc API

js/background.js, js/modules/loki_message_api.js, js/modules/loki_p2p_api.js, js/modules/loki_snode_api.js, libloki/api.js, libloki/test/node/loki_p2p_api_test.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js
Refactored the pinging logic to handle a couple edge cases better
Ttl for online broadcast messages is now only 1 min
More sensible variable names for ping related things
Now ping our contacts that go offline every 2 mins to check if they are back online
Ping our contacts if they sent us a storage server message in the last 2 mins
Along the way I stumbled across a couple bugs in the snode logic that would cause the nodes to always be removed on the first error rather than trying 3 times, and changed the logging to print a warning for the first 2 failures of a snode and then an error when it is removed from memory
Although I didn't end up actually doing a debounce for the pings (because it would have made the system less reliable), this resolves #191 
Also fixes #192 
Tried a bunch and …
=> Optimise pinging

js/modules/loki_message_api.js, libloki/local_loki_server.js, libloki/test/node/local_loki_server_test.js
Update p2p messages to follow the same endpoint format as storage server. Clean up message_api a lil bit and updated tests
Implements #206 (And sets up for #174)
=> P2p using rpc endpoint

.gitlab-ci.yml
A couple months ago the output folder for the windows builds was set to release, this needs to be reflected in the folder that gitlab uploads after building
=> Fix windows gitlab cd

js/background.js, js/models/conversations.js, js/models/messages.js, js/modules/loki_message_api.js, libtextsecure/message_receiver.js, stylesheets/_modules.scss, ts/components/conversation/Message.tsx
Resolves #190 
Rather than changing the message colour, we just add a `p2p` message in the meta data.
=> Added p2p message styling

js/modules/loki_snode_api.js
After a lot of poking around I think this is all we need
This is a bit of a bandaid solution for now because we are just hard coding the dns server to localhost, while in reality lokinet could be configured to bind to a different address
Had some chats with Ryan and hopefully we will be able to reuse some of his node stuff he is doing for the launcher which bundles lokinet in and then we could always ensure that lokinet is installed with the messenger and could run our own instance with whatever config we want
=> Fix resolution for windows

package.json, yarn.lock
The new version seems to fix #218.
When clicking on "disappearing messages" the submenu now stays open.
But the whole thing is highlighted in blue, apparently this is a chrome thing to improve accessibility.
=> Upgrade react-contextmenu to 2.10.0

app/sql.js, main.js
Even though the `db` variable was null (never assigned), there was a database instance being created when a password attempt was made
For some reason windows really didn't like this while other OS's thought it was chill
Also added an await and a null check for just in case
Fixes #216
=> Fix windows database crash

preload.js
I didn't realise there were 2 different windows between processes and I shouldn't have removed this
=> Fix ttl error I introduced

package.json
These fields seem to be used for the release binary, at least on Windows.
=> Replace mentions of Signal in package json

js/conversation_controller.js, js/models/conversations.js
The `initialize` function is called for every instance of a conversation created, which happens _a lot_, so starting a timer for those temporary conversation instances/copies doesn't make sense.
Also, I'm guessing we should save to database right after setting the `unlockTimestamp`?
=> Fix multiple friend request timers instantiated

js/models/conversations.js, libloki/friends.js
Seems a big convoluted so if you guys think of a more straightforward way to do this please comment ;)
To summarise:
* when friend request expires, set the `friendRequestStatus` to `requestExpired` instead of `None`
* when friend request is accepted, set all friend request messages that are `pending` or `expired` to `accepted`
Still feels weird to have 2 different statuses tho.
Fixes #172
=> Add requestExpired state to Friend Request state machine

js/modules/loki_message_api.js, js/modules/loki_rpc.js, libtextsecure/http-resources.js
Include long polling header for retrieve messages
Extend retrieveMessages timeout to 40 seconds, reduce default tmeout to 5 seconds
Remove dev/prod poll time difference now that we want to start new requests quickly since we aren't polling constantly
TODO: Now that we are not polling constantly, it would be nice if we just had 3 (or whatever) poll calls that all independently started a new request any time they got a response rather than the current system where they are all made in the same call which only returns once they are all complete
Thought about this for a bit and a nice way to modify the current implementation to do so didn't seem straight forward, especially with the online/connected stuff :thinking:
=> Long polling

ts/test/types/Attachment_test.ts
Node tests were breaking locally (but not on travis surprisingly).
~The white list tests were broken because `URL` is not defined globally when running mocha, but it is in nodejs (URL is a global in nodejs > v10.0)~
EDIT: The whitelist issue only occurs when running node < 10.0. Turns out I was running node 8.10 and we also fount out that running the tests as sudo might pick a different node version! So reverted the change since we target node 10.13 in the nvmrc.
Hopefully this is the last attempt at fixing the timestamp/filename test.
=> Fix node tests

appveyor.yml
That line seems to never have succeeded?
=> Skip `lint-deps` on appveyor to prevent build failure

js/modules/.eslintrc, js/modules/loki_message_api.js, libtextsecure/http-resources.js
*Disclaimer: untested at this stage, until further notice this PR is just for feedback on the new code flow brought by the refactoring.*
Currently the concurrent connections are always started together, meaning that the fastest request needs to wait for the slowest request to return before it can start over.
This PR basically makes all concurrent connection loop independently of the others.
From top to bottom,
* In `pollServer()` we do a blocking call `await server.startLongPolling(...)` which encapsulates everything. This call never returns as long as everything works fine, but does return or throw if something is wrong (like lokinet/DNS issues) which requires to restart from scratch. In that case, we catch any exception and call `pollServer()` again after some time.
* in …
=> Refactor long polling for better concurrent requests

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, js/modules/loki_p2p_api.js, js/modules/loki_rpc.js, libloki/test/node/loki_p2p_api_test.js
There were a few minor cases that we were missing when checking whether we should ping or just mark the user as online.
This PR simplifies that logic down according to the following diagram:
**EDIT: The image is missing a connection between `Was a user marked as online before?` and `Ping contact`**
Here we assume:
1. When pinging, if it succeeds then we set contact to `online`
2. When we mark the contact as online then we reset their ping timers
3. We always save the latest details
=> Updated pinging logic.

js/background.js, js/models/conversations.js, js/models/profile.js, libtextsecure/sendmessage.js, protos/SignalService.proto, test/models/profile_test.js
We were using signal `Contact` before but we didn't really need any other unnecessary fields.
Also if in the future we want to add a custom field (E.g loki wallet address) then we only modify the proto that we made and not the one signal has, which may stop conflicts occurring (though the chances are low)
=> Convert profile field in DataMessage to use LokiProfile

app/config.js, js/modules/loki_message_api.js, js/modules/loki_snode_api.js, libloki/crypto.js
Next step is having the storage server sending the signature of its certificate to allow the client (messenger) to verify it post-handshake.
=> Make unverified https queries to the snodes

config/default.json, js/modules/loki_message_api.js, js/modules/loki_rpc.js, js/modules/loki_snode_api.js, main.js, preload.js
Make the messenger send and receive to clearnet IP instead of snode addresses
Currently there is just the single hardcoded seed node, probably will add more in the future and choose randomly each time
We use the seed node to populate a list off (currently) every snode, we then use *that* list of snodes to randomly select from when we would normally use random.snode
Closes #292
=> Clearnet seeds

js/background.js, js/modules/loki_message_api.js, js/modules/loki_snode_api.js, preload.js
Now that the successful request tracking is happening in loki_message_api I have tried to clean up snode_api
I have stopped differentiating between our snodes and contact snodes which simplifies things
I moved the instantiation of LokiMessageAPI to background.js so I have access to storage and can grab our key in the constructor
Fixed a big where `lastHash` !== `lashHash`
=> Refactor snode api

js/modules/loki_message_api.js, libloki/api.js
These will likely be clearnet only changes where we expect requests to ip addresses to be quite consistent
The first true part seems a little back hacky because of the raw promise handling but it's also pretty cool
This PR is to smooth the UX for the clearnet where we can be pretty sure that failures are caused by snodes not being accessible so we shouldn't bother trying for a long time
=> Remove nodes after 1 failure and only wait for a single successful send

js/modules/loki_message_api.js, libtextsecure/outgoing_message.js
Try to refresh the swarm list for a contact once for outgoing messages if all connections fail
The main use case for this I can think of is clients messaging contacts for the first time in a long time
The swarm list stored in the database might be all nodes that are now deregistered so all the requests will fail, but if we grab a new list once then the fresh nodes are likely to succeed
Also use 3 connections for outgoing messages now that we have large swarms on the testnet
Also we weren't awaiting the recursive call to sendMessage if the difficulty changes, which I'm pretty sure could cause the UI to do some weird stuff
=> Refresh once

js/modules/loki_message_api.js, libtextsecure/http-resources.js, libtextsecure/message_receiver.js
Message receiver now closes httpPollingResource, which resolves a promise informing the long polling connections to stop because new ones will be created
=> Start attempt at closing long polling connections when offline event is triggered

app/sql.js, js/models/conversations.js
It would break all the databases of the current testnet messengers but we might want to look into moving all the other loki related database stuff (which was put into some of the old schema versions early on when we had a worse idea of how everything worked...) into this versioning model
=> Add loki schema versioning and create new public conversation

js/models/conversations.js, js/models/messages.js, js/views/inbox_view.js, libloki/api.js, libtextsecure/message_receiver.js
Previously we were sending empty messages to trigger things like disappearing messages and friend request accepts. But these were getting filtered out after updating friend request status (so disappearing messages udpates didn't get fully parsed), now we send a broadcast message instead.
Also fix small bug where deleting a contact kept the (now removed) conversation open
Everything seems to be working as expected but could potentially have some unintended consequences?
First thing that comes to mind is we might start triggering ping events more than we need?
Closes #348
=> Fix disappearing messages and deleting contact

config/default.json
This fixes link previews. We don't have any http proxies on any snode (random.snode)
=> fix link previews

app/sql.js, ts/components/conversation/ConversationHeader.tsx
Use 'name' instead of 'profile' for public group
Update conversation header to read the name again
=> Display groupname

background.html, js/views/beta_release_disclaimer_view.js, js/views/inbox_view.js, test/index.html
Simply checks the key-value storage at startup for `betaReleaseDisclaimerAccepted`.
If falsy, then display the modal. When the modal is accepted, it writes down a `true` to that same key in the storage.
HTML will most probably need some love, but this PR is mostly about getting the code at the right place.
=> Add one-time disclaimer at startup for beta release

_locales/en/messages.json, js/background.js, js/models/conversations.js, js/settings_start.js, js/views/settings_view.js, libtextsecure/account_manager.js, libtextsecure/outgoing_message.js, main.js, preload.js, settings.html, settings_preload.js
- enables typing indicators by default (and adds an option to disable them)
- changes ttl for typing indicators to 1 min
=> Add a toggle option for typing indicators; use short ttl for them

js/models/conversations.js
Prevents read receipts from being sent for friend requests. Closes #366.
=> Only send read receipts if friends

js/views/network_status_view.js, libtextsecure/http-resources.js, libtextsecure/message_receiver.js, test/views/network_status_view_test.js
Remove empty event trigger, doesn't seem to be required any more but could be wrong
Looked through upstream signal and doesn't seem relevant to call every time we poll
=> Delay disconnected status and stop emitting empty events

background.html, js/views/standalone_registration_view.js, libloki/modules/mnemonic.js, stylesheets/_global.scss
Show the mnemonic error message on the page, in a consistent manner with the password validation.
Plus a couple of minor improvements along the way.
=> Report mnemonic errors instead of silent failure

app/sql.js, js/background.js, js/models/conversations.js, js/models/messages.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_public_chat_api.js, libtextsecure/outgoing_message.js
Revert the sending of message UUIDs from earlier and instead add a server id field to messages which is only used for public chats
This will allow us to send delete requests for a particular server/channel/messageServerId and have all the clients know which message this is for
=> Use server id

libtextsecure/account_manager.js
The validation of the pubkey (as a hex string) currently calls `conversationController.getOrCreateAndWait` which actually saves the conversation to the database 😱 regardless of whether the string was a valid pubkey or not.
The goal here is obviously to save the conversation to database _after_ the validation succeeded.
=> [multi-device] Fix pubkey validation

app/sql.js, js/modules/data.js, libloki/api.js, libloki/crypto.js, libloki/storage.js, protos/SignalService.proto
This PR makes multiple changes to the db table and proto message, mainly adding getters and differentiating between the request signature (provided by the secondary device) and the grant signature (provided by the primary device):
- Allow updating authorisation in DB (with `INSERT OR REPLACE`) typically when an authorisation progresses from "requested" to "granted"
- Add unique index to `secondaryPubKey` since a pubkey can be linked to only one other primary key
- Removed `signature`  from table and add `isGranted` instead (the signatures are actually in the json field since we never need to query by signature)
- Add optional filter to retrieve authorisation only if it has a grant signature (allows to differentiate authorisation state between requested and granted)
- Add additional …
=> [multi-device] DB and proto changes

js/background.js, js/views/inbox_view.js, ts/components/MainHeader.tsx, ts/state/ducks/user.ts, ts/state/selectors/user.ts, ts/state/smart/MainHeader.tsx
Add a menu item "Pair new Device" if device is not a "secondary device".
To allow hiding this item after the secondary device registration succeeded (which happens after the menu is constructed), I have added `isSecondaryDevice` to the user props.
=> [multi-device] Display "Pair New Device" in menu

ts/components/MainHeader.tsx
Noticed while debugging that the main header was being constantly redrawn.
This was due to the clipboard code updating the component state every 100ms without checking if the value actually had changed.
=> [multi-device] Fix main header being redrawn every 100ms

background.html, js/views/app_view.js, js/views/device_pairing_dialog_view.js
This PR adds the UI modals that appear when clicking on the "Pair new Device" item in the menu.
There are 3 steps:
- Waiting for request to come through
- Request received, requires user to discard or accept the request based on the secondary pub key
- Message sent/error. User can only click OK. If there was an error, the user should start over.
Again, events are handled via `Whisper.events` to allow decoupling.
TODO: replace hard-coded strings with `i18n` translation thingy (in another PR)
=> [multi-device] UI for accepting pairing request on Primary devices

background.html, js/views/standalone_registration_view.js
First iteration for UI for secondary device registration.
Also, re-ordered the accordion to show the default pane "Register a new account" on top.
Note:
The line:
`Whisper.events.trigger('userChanged', { isSecondaryDevice: true });`
is part of another review, but didn't want to exclude it to prevent forgetting it!
It basically forces the left pane UI to update and hide the "Pair New Device" item in the menu dropdown.
TODO: the "Link" button should be disabled while waiting for the authorisation to come through, or until timeout.
=> [multi-device] Secondary device registration UI

libtextsecure/message_receiver.js
The control flow starts at the bottom of the diff and splits in 3.
- the authorisation is a pairing request (primary device side)
- the authorisation is addressed to us (secondary device side)
- the authorisation is a pairing grant (third-party contact)
The authorisation is saved only if valid.
Note:
`Whisper.events` are used to propagate events across the application:
- `secondaryDeviceRegistration` event: we (the secondary device) have received the grant authorisation from the primary device. This makes the UI transition from the registration page to the inbox page.
- `devicePairingRequestReceived` event: we (the primary device) have received a pairing authorisation request. This will trigger the UI to prompt the user to accept the pairing if the pairing modal window is open, otherwise …
=> [multi-device] Handle incoming pairing authorisation message

js/models/conversations.js, js/modules/loki_message_api.js
The secondary device registration step requires to send and receive messages before lokiP2PApi is instantiated, which happens after the registration is done.
=> [multi-device] Allow receiving and sending messages before lokiP2PApi is defined.

js/background.js, js/delivery_receipts.js, js/models/messages.js
Ensure messages coming from secondary devices are forwarded to the primary conversation.
There is multiple occurrences of the same check because it's required for typing indicator messages, normal messages, read receipts, etc. Some code paths might see the same check twice, but I figured it keep things more modular as well (you could still call an intermediary function without knowing or caring about the substitution)
=> [multi-device] Display incoming messages in the primary device conversation

libloki/storage.js, libtextsecure/outgoing_message.js
- Re-visited the existing Signal logic that sends a message to all the devices linked to a primary pubkey. I have replaced `deviceIds` with `devicePubKeys`, which includes the primary device pubkey.
- Make secondary device attach the authorisation to any outgoing friend requests
- Show the message as sent if sent to at least one message
=> [multi-device] Outgoing messages

js/background.js, js/registration.js
This PR ensures the inbox is shown only when the secondary device registration process is truly complete.
The current condition only checks for the existence of the key pair, which is not enough for secondary devices since they were created to send the authorisation request to the primary device. For secondary device, we also need to check the `secondaryDeviceStatus`, which is cleared after the registration is done.
=> [multi-device] Prevent showing inbox if secondary registration is ongoing

js/views/standalone_registration_view.js, libtextsecure/message_receiver.js
- Need to bind `onSecondaryDeviceRegistered` to `this` because it's passed as callback
- Use the correct type for request vs grant signature validation
- Only reject request authorisation sent by the secondary pubkey to itself (edge case)
=> [multi-device] Fix bugs revealed during reviews

app/sql.js, js/models/conversations.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_public_chat_api.js, libloki/crypto.js, libtextsecure/outgoing_message.js, libtextsecure/sendmessage.js
Use the public chat api to get metadata in the sending pipeline rather than from the conversation
And retrieve the token from the public chat api (in #448) when sending
=> [Public Authentication] Auth sending

js/views/standalone_registration_view.js, libloki/api.js, libtextsecure/outgoing_message.js
Since the pairing process should be done with both devices online, the pairing request message should have a short TTL. I've set it to 2 minutes. The timeout for receiving the grant message back on the secondary device is 1 minute, so this leaves 30 seconds for messages to travel in each direction.
Also, I've replaced a `if/else if` statement with a `switch` and moved that into a local function to allow returning the values. This makes the thing slightly more robust against forgetting `break`'s, even though usually IDE's and linters pick this error up easily.
=> [multi-device] Shorter TTL for pairing requests

_locales/en/messages.json, app/sql.js, js/background.js, js/models/conversations.js, js/models/messages.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_public_chat_api.js, js/views/conversation_view.js, ts/components/conversation/Message.tsx
=> Public delete

js/models/messages.js, ts/components/conversation/Message.tsx
Add option to copy pubkey from public chat messages so you can easily add friends from the chat
=> Add right click option to public chat messages to copy pubkey of sender

background.html, js/views/standalone_registration_view.js, stylesheets/_global.scss
- Disabled button after pressed, until timeout or an error occurred.
- Display public key
- Display timeout count down
Also ensure the `secondaryDeviceStatus` is only set while waiting for a response.
So it's cleared at startup and also if the user registers as a new account.
=> [multi-device] Secondary registration UX changes

js/background.js, js/models/conversations.js, js/modules/loki_public_chat_api.js, js/modules/loki_rss_api.js, js/modules/loki_snode_api.js
Quick and easy, just want to save the id of the last message we retrieve so we can pick up where we left off on app restart
Also snuck in a cheeky `active_only` flag to the bootstrap node request
=> Save the last retrieved message for public chats on the conversation

app/sql.js, js/background.js, js/modules/data.js, js/rotate_signed_prekey_listener.js, js/views/standalone_registration_view.js
- Make sure we clean up right before we register a new account
- Add `removeAllConversations` to data/sql
- Allow to stop and restart `Whisper.rotateSignedPreKeyListener`
- validate primary public key before registering new account
- Add missing listeners (ties up previous PR's)
=> [multi-device] Cleanup after failed registration

js/models/messages.js, ts/components/conversation/FriendRequest.md, ts/components/conversation/FriendRequest.tsx
Fixes  #355.
Then after accepting:
=> Display timestamp for friend requests

js/modules/loki_snode_api.js
I noticed the `lastHashes` table was showing all `NULL` for the snode and hash rows.
Hopefully this fixes issues related to  UNIQUE key constraints with seen message hashes 🤞 
The related code is in sql.js:
```js
async function updateLastHash(data) {
const { snode, hash, expiresAt } = data;
```
=> Fix last hash all being NULL in database

app/sql.js, js/background.js, js/modules/data.js, js/signal_protocol_store.js, js/views/standalone_registration_view.js, libloki/api.js, libtextsecure/message_receiver.js, protos/SignalService.proto
Reuse the existing sync mechanism from signal, at least the receiving side.
The sending side needed to be written, it's mainly a matter of wrapping proto objects inside each others and getting the bytes in the right format (byteBuffer vs ArrayBuffer vs Uint8Array).
I've added a new `data` field in the proto to bypass the need for `attachmentPointer` (Signal treats syncs as attachements that need to be downloaded separately) and added a `nickname` field in contact details.
=> [multi-device] Share contact upon authorising secondary device

js/background.js
This PR should fix `SQL unique constraints` errors on seen message hashes (bug specific to multi-device branch)
Basically every time the secondary device registration process is triggered, new instances of the API objects are created. But the old objects aren't automatically garbage collected, especially if they were waiting on network events (long polling).
This was basically creating multiple instances of the lokiMessageAPI, which each their own JobQueue, so the calls to save a hash and retrieve the hashes was not atomic across the two JobQueues.
This PR ensures we only instantiate those objects once.
=> [multi-device] Ensure API objects are inited only once

js/background.js, js/models/conversations.js, js/models/messages.js
We need to ensure we are treating incoming public chat messages from ourselves as outgoing messages and we also need to make we have all the message data required to detect duplicates
=> Fix duplicate detection for sent messages in public chat

js/modules/loki_public_chat_api.js
I realised we were hitting the database a ton of times every few seconds, turns out we were constantly trying to delete all the messages that have been deleted because we were exiting a while loop before updating the deletedLastId
=> Make sure we are always updating the last deleted id

js/link_previews_helper.js, ts/components/JazzIcon/JazzIcon.tsx
Since signal moved to React, any update to the message component triggers a link preview fetch if it didn't exist. This meant that for every link preview we generating about 3 or 4 requests which then save the image to disk. So for each link preview we had 3-4 images on disk.
To fix this we just create a local memory cache and return already fetched requests from there.
=> Fix unnecessary link preview fetches.

app/sql.js, js/modules/data.d.ts, js/modules/data.js, ts/components/MainHeader.tsx, ts/state/ducks/search.ts, ts/types/Search.ts
This PR prevents users to send messages directly to their other devices.
They should do it via the "Note to self" (aka their own conversation).
So in case they type one of their other device's pubkey in the searchbar, it actually shows the "Note to Self" conversation.
This works for other contacts too: Searching any paired pubkey will return the primary device conversation only.
=> [multi-device] Search returns primary device conversation

app/sql.js, js/background.js, js/views/app_view.js, js/views/device_pairing_dialog_view.js, js/views/standalone_registration_view.js, libtextsecure/message_receiver.js
This PR fixes the following bug:
- the secondary device sends a first pairing request with a signed prekey id = 1.
- after timeout, the secondary device is allowed to re-send a request. Signed prekeys are wiped and a new signed prekey with id 2 is sent.
- the secondary device accepts but uses the signed prekey with id 1.
Also, improves cleaning up bundles when requests are not accepted.
Removed `removeAllPreKeys` in `resetRegistration` since that already happens inside the registerSingleDevice function.
=> [multi-device] Ensure the latest contact signed prekey is used

_locales/en/messages.json, background.html, js/views/app_view.js, js/views/device_pairing_dialog_view.js, libloki/storage.js, ts/components/MainHeader.tsx
Renamed "Pair new Device" to "Device Pairing" in main menu.
Added a new view in the pairing modal, showing a list of paired devices.
Going through the whole pairing procedure takes the user back to the default view, where the new pubkey can be seen in the list.
Also used locale messages for text.
=> [multi-device] Display list of paired device in modal

background.html, js/modules/signal.js, js/views/conversation_view.js, js/views/member_list_view.js, stylesheets/_mentions.scss, stylesheets/_variables.scss, stylesheets/manifest.scss, test/index.html, ts/components/conversation/MemberList.tsx
Decided to split the PR for mentions into two. This is part 1 that includes the following:
- typing `@` brings a group member selection element into view (scrollable, can be navigated with up/down arrows)
- the word directly following `@` is considered the search query used for filtering the list of members
- `Tab`, `Enter` or left mouse click selects a member, which replaces the query with the member's pubkey.
In the upcoming PR I will work on the presentation of pubkeys (replace them with Profile names). Probably will need to rework the input element to allow formatting. Also, currently I obtain the list of members from the conversation model. This will need to be changed to use a server endpoint for the full list of members that joined the chat.
=> Add UI elements for searching and selecting members in a group chat

js/modules/loki_public_chat_api.js
This PR makes it so any similar messages fetched through the public chat will be ignored if:
The same author posted the message, The message has the same text AND the message was sent within 10 seconds.
This will alleviate the display of spam somewhat but is not the perfect counter measure as someone could spam the same message every 10 seconds.
Fixes #504
=> Public chat duplicate message fix

app/sql.js
The `active_at` field determines if the conversation should be visible or not (when null), and gets assigned a timestamp when receiving messages.
This fixes the edge case where there is no message (e.g. they were all deleted or filtered out due to invalid signatures) which never triggers the creation of the active_at field.
=> set active_at to now() for public channels

app/sql.js, js/background.js, js/modules/data.js, js/modules/loki_file_server_api.js, libloki/storage.js
This PR
- wraps the existing `setOurDeviceMapping(mapping, isPrimary)` around a new function `updateOurDeviceMapping()` which fetches the mapping and call the former.
- Renames a bunch of function `***ForPubKey` to `***ForSecondaryPubKey` to be more explicit
- Adds missing `getGrantAuthorisationForPrimaryPubKey` that will be used in a future PR
- Makes the authorisation getters from `Signa.Datal` return the signatures as is (base64) and makes the getters from `libloki.storage` converts them to ArrayBuffer.
=> [multi-device] Add high-level function to update device mapping

app/sql.js, js/modules/data.js, js/views/standalone_registration_view.js
During second device registration, the logic has to reset the database after any failures.
But since the sql migrations only runs the very first time, we can't remove the public conversations that we want to keep.
=> [multi-device] Remove private convs only

js/views/device_pairing_dialog_view.js
I noticed a bug after a failed pairing, the primary device would keep showing the error message when trying again to receive a new pairing request. Turned out some the internal state was not reset.
=> [multi-device] Reset pairing view after error

background.html, js/views/standalone_registration_view.js
As discussed with Mik and Niels, when registering the secondary device, the timeout on desktop is not necessary and will actually lead to a mismatched pairing more easily (i.e. primary thinks the pairing is successful while the secondary actually had reset after a timeout).
Instead, we now show a cancel button that allows the user to manually cancel and then retry.
=> [multi-device] No secondary timeout

js/modules/loki_file_server_api.js
This is probably technical debt, but `libloki.storage.getGrantAuthorisationForSecondaryPubKey` and `Signal.Data.getGrantAuthorisationForSecondaryPubKey` aren't doing exactly the same.
The latter returns the authorisation from the db as is (signatures as base64) while the secondary converts them to array buffers.
Anyway, in this case we want to send the signatures as base64 to the file server.
=> [multi-device] Fix signatures being sent to file server as arraybuffer

js/models/messages.js, js/modules/data.js, js/modules/loki_file_server_api.js, libloki/crypto.js, libloki/storage.js
- small refactor here and there
- when a device accepts a friend request, save all the device mappings related to the other device's primary device
- fixes for bugs discovered during testing
=> [multi-device] Save device mappings upon accepting friend request + various fixes

background.html, js/views/standalone_registration_view.js
QoL with auto focus display name box and enter/esc key functionality on profile screen. Restrict display name characters to alphanumeric (easy to work around)
fixes #528
=> Restrict username characters

config/development-2.json, libloki/api.js, package.json
Decision was made for this release to *not* share contacts with your paired devices because mobile won't get there in time and it is better to remain consistent cross-platform
=> [multi-device] Disable sharing of contacts (TEMPORARY) and add start-multi2

js/views/conversation_view.js, js/views/member_list_view.js, preload.js
When a member is selected, we create a mapping from "handle" (usually their profile name) to their pubkey. If multiple members with the same profile names are selected, one of the conflicting handles is augmented with a corresponding shortened pubkey (we use as many characters from the pubkey as necessary to avoid ambiguity). Before a message is sent, all handles are replaced with their corresponding pubkeys, and the mapping is reset.
The input/compose GUI element now has custom handling of arrow, delete and backspace keys. In particular, we make sure that a mention is treated as a single indivisible element, so if any action would result in a caret being positioned inside a mention, it will be moved either to the end or the beginning of the mention (whichever is more natural). We don't, …
=> Show mentions as profile names and treat them as indivisible elements

stylesheets/_mentions.scss
This should improve how member list is rendered on small screens (or if the window is not full-screen).
=> Prevent chat member's pubkey from overflowing

js/models/conversations.js, libtextsecure/message_receiver.js
Now that we have a single conversation containing messages coming from multiple devices, we want this conversation UI and features like read receipts to interact as expected for any combination of devices that you are friends/not friends with, not just the primary
=> Add isFriendsWithAnyDevice and use it in relevant places

_locales/en/messages.json, js/models/messages.js, libloki/api.js, libloki/storage.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js
(Forgot the multi-device flag for the other PRs...)
The meat of the multi device work I did
I think the additions for `saveAllPairingAuthorisationsFor` are redundant, but I need to get some fresh eyes to figure out the minimum amount of calls that are required
- Trigger friend request accept/received etc for the relevant secondary conversation rather than the primary
- Build automatic friend request if you are not friends with one of the devices for any outgoing message (needs to be throttled later)
=> [multi-device] Robust sessions

libloki/crypto.js, libtextsecure/account_manager.js, libtextsecure/message_receiver.js, protos/SignalService.proto
We Infer pairing message type from the content and not by the field set in the protobuf
=> Fix cross platform device linking

js/models/conversations.js, js/views/conversation_view.js
- Deleting of failed messages now works and it doesn't ask for user confirmation
- Fixes #587
=> Delete public chat messages locally if not stored on the server

_locales/en/messages.json, js/views/conversation_view.js, stylesheets/_modules.scss, ts/components/conversation/ConversationHeader.tsx
- shows "(not friends)" instead when no FR is sent
- adds some styling (margin and font colour) to that status
- fixes #555
=> Fix incorrectly showing friend request as pending

js/views/device_pairing_dialog_view.js, js/views/standalone_registration_view.js, libloki/modules/mnemonic.js
Since the user has no ways to know the paired device's pubkeys, show the secret words instead.
Also, refactor the creation of the secret words into its own function.
The next step is allowing the primary device to define an alias for those secondary devices.
=> [multi-device]show pairing words on paired device list

preload.js, ts/components/MainHeader.tsx
- removes `create private group` option from UI if `window. lokiFeatureFlags.privateGroupChats === false`
=> Add a feature flag for private group chats

_locales/en/messages.json, background.html, js/background.js, js/views/app_view.js, js/views/device_pairing_words_dialog_view.js, ts/components/MainHeader.tsx
As discussed about revoking, we need a way to identify the paired devices since the secondary device pubkeys are hidden to the user.
This adds a menu item "Show pairing words" that displays a dialog.
=> [multi-device]Show secondary secret words

_locales/en/messages.json, background.html, js/views/device_pairing_dialog_view.js
Note that the alias is mandatory and that the "ok" button is disabled if the input field is empty.
=> [multi-device]Allow primary device to assign local aliases to paired devices

js/background.js, libtextsecure/message_receiver.js
The nickname/display name doesn't currently work on secondary devices.
This is because the nickname received from the primary device is applied to the "real" secondary conversation, but the UI receives `ourNumber` which is set to the primary pubkey, and looks up teh primary device's conversation to get the nickname, which is empty.
Basically the inbox UI could keep our "real" number, but having the `phoneNumber` field always show the `primaryDevicePubKey`.
This is a bit spaghetti soup so suggestions welcome.
=> [multi-device] Fix secondary nickname

libloki/modules/mnemonic.js
This fixes the issue where the words on mobile and desktop were different.
=> Use first 3 mnemonic words instead of the last 3 when displaying secret words.

app/sql.js, js/modules/data.js, js/modules/loki_app_dot_net_api.js, js/views/conversation_view.js
Still not sure why the code was leaky.
~~But the solution was easy: the conversation view already has a reference to the conversation model via `this.model` which already has a `.messageCollection` which has `.models`...~~
Solved by adding a new SQL function to get all unique pubkeys in a public conversation.
Then get profile name from their respective conversation. The id is only used as a unique identifier by React, so using the pubkey works.
Other changes are self explanatory.
There still might be other leaky parts of the code. Still investigating.
EDIT: memory comparison:
BEFORE
note the horizontal grey line shows 500KB
AFTER
note the horizontal grey line shows 10KB
=> Fix recurring memory leak in mentions

js/views/bulk_edit_view.js, js/views/conversation_view.js
The react component tied to the bulk edit view can be instantiated once at init, then have its props (the number of selected messages) updated on request, instead of re-instantiating a new react component in the render function.
=> Prevent instantiating a new BulkEdit react component with every click

js/views/device_pairing_dialog_view.js
Cap number of devices to 1 by disabling the "pair new device" button:
=> [multi-device]Cap paired devices to 1

stylesheets/_conversation.scss, ts/components/conversation/FriendRequest.tsx, ts/components/conversation/Message.tsx
Message highlighting PR slightly reworked `<div>` containers for messages and used the same css rules for private and group messages. However it seems that in the presence of avatars public messages started to look too far off the left edge.
In this PR I re-added a special rule for public messages and also added margin for the friend request bubble.
=> Fix incorrect margins for public messages and friend request bubbles

js/background.js
`primaryDevicePubKey` is currently set only at registration time.
This PR ensures that this value exists in storage even if the account was already created with an older version of the messenger.
=> Ensure primaryDevicePubKey is always defined in storage

js/views/conversation_view.js
Might need to test this on Windows/Linux but it should work (works on MacOS if I disable its default behaviour for Ctrl).
=> Jump words with Ctrl and arrow keys

libtextsecure/account_manager.js
This PR fixes the following use-case:
Mobile primary. Desktop secondary.
During pairing, Desktop needs to re-send the request (e.g. because Mobile wasn't accepting requests) by cancelling and re-sending the request.
The request arrives on Mobile, and is accepted.
Desktop would then print
`Error: Received a preKeyWhisperMessage (friend request accept) from an unknown source`
The reason for this is that when the user cancels the pairing request, it deletes all the prekey bundles stored in the database. But on mobile, although the first pairing request was ignored (because the linking modal was not open), the prekey bundle was still stored. Then when the second pairing request arrives, the second prekey bundle doesn't overwrite the first one. So when the pairing is accepted, the first prekey …
=> Prevent prekeys to be deleted when re-sending pairing request

js/background.js, js/modules/loki_file_server_api.js, js/views/app_view.js, js/views/device_pairing_dialog_view.js, libloki/api.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, preload.js, protos/SignalService.proto
The existing unpairing code only updated the primary device mapping locally and on the file server.
This PR adds logic to send a special message with a UNPAIRING_REQUEST flag to the secondary device (4days TTL), as well as the handling logic on the receiving end.
Upon receiving the unpairing message, we check if it's legit and then clear our mapping from the file server and then run the "clear all data" code.
What is missing here is the flag to trigger the message at the next startup, explaining why the account was erased.
=> Sending and handling of special UNPAIRING_REQUEST message

background.html, js/views/device_pairing_dialog_view.js
Added QR code in the dialog view when waiting for secondary device message.
I decided not to show it prior to ensure the secondary device sends the request only when the primary device is listening for them.
I checked that the QR code is correct by comparing it with the one shown via "Show QR code" in the menu.
Wrapped the div around `<div class="qr-dialog">` to get it centered in the dialog.
=> Show pubkey QR code in primary pairing dialog

js/views/standalone_registration_view.js
The issue 385 is already resolved. This commit sets up the same behavior
for the other sections of the registration page (i.e. the mnemonic and
the link device sections).
Fixes #385
=> Update input focus on registration page

js/models/messages.js
This addresses the problem of "Original message not found" that can manifest itself in bulk loading of  messages (e.g. from the public chat server), resulting in a quoted message not being saved to the database when the quoting message is looking it up.
I went with the simplest solution: request the missing quoted message again after a short delay (doing it a few times with exponential backoff) and updating the quoting message accordingly.
=> Check again for quoted messages after a short timeout

_locales/en/messages.json, js/models/messages.js, js/modules/loki_app_dot_net_api.js, ts/components/conversation/Message.tsx
Added functionality to ban users from public chat as Moderator.
Please write a summary of your test approach:
Tested on public chat via 2 test cases; API request failed. API request succeeded.
UI responds with toast on success or failure.
=> Public ban

background.html, js/background.js, js/models/messages.js, js/modules/signal.js, js/views/app_view.js, js/views/conversation_view.js, js/views/user_details_dialog_view.js, stylesheets/_conversation.scss, stylesheets/_index.scss, ts/components/Avatar.tsx, ts/components/EditProfileDialog.tsx, ts/components/UserDetailsDialog.tsx, ts/components/conversation/ConversationHeader.tsx, ts/components/conversation/Message.tsx
Make the avatars (in the conversation view) clickable to show a modal with details about the user clicked:
Show the name, the avatar and the public key of the user.
A button can be used to start a conversation with this user directly.
Should I add a "Copy pubkey" button? The pubkey is selectable already but still...
This behavior needs to be included to the issue #656 once ready.
Relates #655
Here is a screenshot (in french)
=> clickable profile

js/background.js, js/models/conversations.js, js/modules/loki_app_dot_net_api.js, js/modules/loki_file_server_api.js, libloki/api.js, libtextsecure/message_receiver.js, libtextsecure/sendmessage.js, ts/components/MainHeader.tsx
- Encrypt/decrypt picture when uploading/downloading
- Prevent downloading our own picture right after having uploaded it (we already have the bytes)
- ~~set `profileSharing` on every conversation to true to enable sending the `profileKey` with every message~~
~~Note that the public chat side of things will come in the next PR.~~
~~EDIT: changes for public chat added in this PR but in a separate commit~~
- set `profileSharing`  to true only before sending a friend request (FR), or after becoming friend, for private chats
- add logic in the AppDotNet API to store our profileKey in the user annotation
- ~~share our profileKey on the public chat only upon sending a message the first time~~
- ~~share our profileKey on the public chat every time it changes, unless we've never sent any …
=> Encrypted profile pic

_locales/en/messages.json, background.html, js/background.js, js/models/conversations.js, js/models/messages.js, js/views/app_view.js, js/views/confirm_session_reset_view.js, js/views/message_view.js, libtextsecure/message_receiver.js, libtextsecure/sendmessage.js, protos/SignalService.proto, test/index.html
- On first message that we can't decrypt we show the prompt and record that we've done that (so we don't show the same dialog for every message)
- On submit, we send an empty message with a `SESSION_RESTORE` flag, so we can display the message accordingly (the session reset will happen in the background in that case)
- If some old friend request is still in the database after we restore from seed, we leave it as is (we can't really distinguish between new and old FR, and old FR won't work anymore), but perform session restoration as above rather than responding to that FR in case we've also received some undecipherable messages from that pubkey.
- I don't use "showConfirmationDialog" because it is ugly (and would require some size tweaking to fit pubkey in one line)
=> Prompting the user to reset session on invalid ciphertext

_locales/en/messages.json, js/background.js, js/models/conversations.js, js/modules/loki_app_dot_net_api.js, js/modules/loki_file_server_api.js, js/modules/loki_public_chat_api.js, js/modules/loki_rss_api.js, js/views/connecting_to_server_dialog_view.js, js/views/conversation_view.js, js/views/create_group_dialog_view.js, package.json, ts/components/conversation/ConversationHeader.tsx, ts/components/conversation/UpdateGroupDialog.tsx
- Make sure public servers are in the conversation tabs (when no messages, not the friends tab)
- updateGroup now works with public chat conversations. When in public chat mode we:
- remove members count for now
- remove friendList
- use different internationalized title
- actually save back to the server
- clean up app_dot_net classes further
- move specific public chat api class into `loki_public_chat_api.js`
- make loki_app_dot_net_api expose the serverAPI class
- make file server take advantage of that clean up
- reorganize channelAPI, so serverAPI isn't dependent on the public chat api
- minor rss fix for an error I observed
- fixed an annoying typo in adn serverAPI's serverRequest()
=> Public Server Moderator QoL improvements

js/modules/loki_app_dot_net_api.js, js/modules/loki_public_chat_api.js
if you token became invalid for whatever right, we had forgot to pass `true` to `getOrRefreshServerToken` to actually get a new token. Fixed that.
Also fixes the /token check on start up, so if it fails, it `forceRefresh` a new token.
improved logging and other minor cleanup.
=> Fix token refreshing

js/modules/loki_app_dot_net_api.js
It seems like `slaveMessages` was still treated like `Object` after it's been changed to `Array`.
=> Fix not showing messages from secondary devices

ts/components/session/SessionClosableOverlay.tsx, ts/components/session/SessionIdEditable.tsx
Auto focuses the input area for the new open chat ID, so the user can start typing it immediately.
=> Auto-focus new open chat input box

config/swarm-testing.json, config/swarm-testing2.json, js/modules/loki_app_dot_net_api.js, js/modules/loki_message_api.js, js/modules/loki_rpc.js, js/modules/loki_snode_api.js, package.json, preload.js
This PR is meant as a demo for using the snode proxy. The main idea is to substitute the nodeFetch call for all snode requests and requests to `file.lokinet.org` with functions that will package the original request and send them to a random snode, the response should be identical (as far a the messenger is concerned) to what we would get without the proxy.
=> Add a feature flag for snode proxy

stylesheets/_conversation.scss, stylesheets/_theme_dark.scss
make the background the same color as the bottom form
a message is displayed and the cursor is set to "not-allowed"
=> fix disabled state of message input on sent friendrequest

js/models/messages.js, js/modules/loki_app_dot_net_api.js, libtextsecure/message_receiver.js, libtextsecure/sendmessage.js, protos/SignalService.proto
Renamed `BACKGROUND_FRIEND_REQUEST` to `SESSION_REQUEST` to match mobile clients.
Don't trigger friend request logic on a group message.
=> Fix session request messages

js/background.js, js/models/conversations.js, libtextsecure/outgoing_message.js, libtextsecure/sendmessage.js
These were uncaught before merging #788 
The issue was that we were forcing all messages to be friend requests if we weren't friends with a user/ didn't receive a friend request. This is correct for private chats but not for group chats as we could potentially have a session but still not be friends with the user.
- Fix friend request messages being sent to users you don't have a session in closed groups.
- Disable typing messages in groups.
- Send out session request messages if you don't have a session with a member in the group.
=> Closed group fixes

js/modules/loki_app_dot_net_api.js
and make it easier to see what endpoint failed on proxy
=> make sure sendToProxy get the textResponse option from submit_challenge

stylesheets/_session.scss
change span css property user-select from none to text and this enables all the copy and paste behaviour
see the original issue post: 
https://github.com/loki-project/session-desktop/issues/801
=> change the user-select to text

.eslintrc.js, js/modules/metadata/SecretSessionCipher.js, libloki/crypto.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, libtextsecure/sendmessage.js
Moved session reset out from `message_receiver` into a custom `LokiSessionCipher`.
I didn't want to modify `SessionCipher` directly since it resides in `libsignal-protocol.js`.
There's also a minor fix that i forgot in #838
=> Refactor session reset handling

js/views/file_input_view.js
Fixed the signal way of checking the file size before adding it as attachment.
max size is 10mb for everything, except for images which are resized.
this limit is enforced per file only, not for a message containing several files
=> show error when user try to add file >10mb as attachment

ts/components/DevicePairingDialog.tsx
we match the android way: when a request you can directly accept or
cancel the whole link process.
=> remove filter request button from linking device

main.js
As suggested, with that old commit in https://github.com/loki-project/session-desktop/pull/336  the "Go to Release Notes" link is broken referencing to "https://github.com/loki-project/session-desktop/releases/tag/1.0.1" for example.
=> Reverting changes in pull #336

libtextsecure/sendmessage.js
The previous check was forcing the keys to be processed, which we don't want.
=> Fix check to see if we have keys or not.

js/background.js, js/models/conversations.js, js/models/messages.js, js/modules/loki_app_dot_net_api.js, js/views/invite_friends_dialog_view.js, libloki/api.js, libloki/storage.js, libtextsecure/account_manager.js, libtextsecure/message_receiver.js, libtextsecure/sendmessage.js, protos/SignalService.proto, ts/components/session/LeftPaneChannelSection.tsx
This PR adds the ability to sync across closed groups.
We also change the following:
- Send contact sync message separately from pairing accept message
- Send 3 contacts at a time during sync to avoid hitting storage server limit (This should be increased the next hardfork)
We also send 1 group per sync message but this should be increased after the next hardfork once the storage server file size limit increases
=> Closed group syncing

js/background.js, js/notifications.js, preload.js
Signal disables notification on start of app to avoid flooding the user with "new message" notifications.
It waits for the server to send a "end of messages" (`/api/v1/queue/empty`) to turn them back.
As we do not have a way to do the same, I just enabled notifications at the start. The inconvenient is it will flood the user on app start/reconnect from network loss.
=> Enable back notifications

js/modules/loki_message_api.js, js/modules/loki_rpc.js, js/modules/loki_snode_api.js, libtextsecure/http-resources.js
- `sendToProxy()` handle non base64 responses from snode
- `getSwarmNodes()` - Hit multiple random nodes and merge lists
- minor optimization: `refreshSwarmNodesForPubKey()` returns filtered nodes to avoid hitting sqlite again
- `initialiseRandomPool()` retries up to 3 times before failing
- `startLongPolling()` logs if pulling from blockchain fails
- include server ip/port in logging for additional manual testing
- log some unlogged exception
basically improves on:
`Loki retrieve messages:  Illegal str: Length not a multiple of 4`
`Loki retrieve messages:  Illegal character code: 32`
to actually give actionable information
=> Snode communication retries and logging improvement

js/background.js
Fixes #893 
The Problem was that a restart was called before cleanupOrphanedAttachments gets called. So cleanupOrphanedAttachments tries to interact with a database, which is already closed. This causes the `Error: Object has been destroyed`-Error.
OS: Windows 10 Pro Insider Preview
=> Move cleanupOrphanedAttachments before restart

main.js
remove org.whispersystems from notifications to match package.json build appId, fixes #952
I still have some additional recommendations in #952 that I can append to this PR if approved.
=> Fix #952: remove org.whispersystems in notifications

js/modules/loki_app_dot_net_api.js, js/modules/loki_public_chat_api.js
setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;` is different from setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` because javascript.
please note that this isn't the correct fix for this code it just makes it "work".
=> make session "work" with .loki tld

package.json
> If you build both ia32 and x64 arch (--x64 --ia32), you in any case get one installer. Appropriate arch will be installed automatically.
=> Enable building win32 binaries.

package.json
Reverts loki-project/session-desktop#980
This makes the installer fail on 64bit machines and increases the installer size unnecessarily
=> Revert "Enable building win32 binaries."

stylesheets/_session.scss
Fixes #968
Add overflow-y auto to session-id-editable so you can see the whole session id.
=> Add overflow-y auto to session-id-editable

_locales/en/messages.json, js/background.js, libtextsecure/message_receiver.js
Showing a toast which does not fade until closed so the user can read the manual to open the device pairing dialog
=> Toast on device pairing request received but in device pairing mode

app/sql.js, js/background.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_rpc.js, js/modules/loki_snode_api.js, libloki/crypto.js, libloki/storage.js, libtextsecure/stringview.js, preload.js
- Disable long-polling
- Onion path building with guard nodes: guard nodes persist in DB; there is a path per every guard node; every path rebuild tries to reuse existing guard nodes
- Added GCM encryption used for every node on the path
=> Client-side implementation for onion requests

js/spell_check.js
=> default to en_US if locale dictionnary is not found

_locales/en/messages.json, ts/components/MainViewController.tsx, ts/components/session/settings/SessionSettings.tsx, ts/components/session/settings/SessionSettingsHeader.tsx
Disable the settings button allowing to linking a new device when the current device is already a current device
=> disable link option on secondary device

.github/PULL_REQUEST_TEMPLATE.md
The Link about "Git Rebase - the Golden Rule" has led to a 404. (Try it)
And the link `clearnet` referenced to the development-branch instead of clearnet.
=> Fix Links in Pull Request Template

main.js, ts/components/session/SessionIdEditable.tsx, ts/components/session/SessionInput.tsx
- integration tests needs the mouse to be able to click on the closed group create button. This means it needs to be visible.
- since my next PR we use JS to inject values in integration testing (to work around a spectron bug), the onChange event doesn't fire, added an onBlue handler to make sure the state value is accurate. This may fix #1021 because this is the exact behavior I caught in the integration test.
=> make closed group create button clickable (via minimum height), onBlur calls onChange

js/background.js
We do this so it doesn't block any of the other communication apis from being initialised.
=> Build onion paths after storage becomes ready

js/modules/loki_app_dot_net_api.js, js/modules/loki_rpc.js, libloki/crypto.js
The solution was simple ...
Signal has 2 curve implementations, a `sync` and an `async`. We were using the `sync` version so the expensive crypto functions were being run on the main thread. The `async` versions pass this off to a worker.
=> Fix CPU usage when using onion requests

libtextsecure/outgoing_message.js
This fixes the issue where desktop sends out a background friend request after accepting a session request.
We will need to get this tested to make sure it doesn't break other logic.
=> Ignore multi device logic when sending background message

config/default.json
Kee and I have confirmed mainnet port on `storage.seed2.loki.network` was fine since 6.x
imaginary.stream change Jason's approval:
https://discordapp.com/channels/408081923835953153/563594234632863754/685282143743901696
=> Update mainnet servers, stop using testnet port

app/sql.js, config/development.json, config/swarm-testing.json, js/background.js, js/models/conversations.js, js/modules/data.js, js/modules/loki_message_api.js, js/modules/loki_rpc.js, js/modules/loki_sender_key_api.js, js/modules/loki_snode_api.js, js/modules/metadata/SecretSessionCipher.js, libloki/crypto.js, libtextsecure/http-resources.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, libtextsecure/sendmessage.js, package.json, preload.js, protos/SignalService.proto
This is not a complete implementation, but most of it is done and this PR is getting big.
Implemented:
- Polling for more than one id (group ids in addition to our identity)
- lastHash is now conversationId-aware
- Group creation and sender key management
- Messages with sender keys are correctly associated with the right conversation in GUI
- A brand new ratchet implementation for use with sender keys (different from Signal's in that it is missing the DH component impractical for groups)
For testing:
```
async function createMediumSizeGroup(groupName, members) { ... }
```
Example:
```
window.createMediumSizeGroup("GroupName", ["0531715c5f8476108b2481c9f42d62943417d795da96f0a7346644401294dba319", "05aaf884bef56a7d0dc044e2c8a330c4d0e2cb3e2cb785b6c169bc9c0beb0fcf21"])
```
Still missing:
- …
=> Medium groups with sender keys (essentials)

_locales/en/messages.json, js/background.js, js/models/conversations.js, js/models/messages.js, js/notifications.js, js/views/app_view.js, js/views/conversation_view.js, libloki/api.js, libloki/test/index.html, libloki/test/messages.js, libtextsecure/message_receiver.js, libtextsecure/outgoing_message.js, libtextsecure/sendmessage.js, package.json, preload.js, ts/components/session/RegistrationTabs.tsx
- refactor `message-receiver.js` so it does not send any messages
- split handleDataMessage is message.js to several sub function
- fix some multi device bugs (triggering session requests on groupSync)
- remove isPing as not used (P2P thing, and p2p was removed already)
- show a toast if the user triggers a new device link while another is still in progress
- add some logs to better follow message being sent/received WIP (with our primary/secondary devices pubkey replaced)
- a public message from ourself is know triggering a 'sent' event -> handled as a syncMessage so from ourself automatically
- comment some useless logs (notification related)
- contactSync: be sure to sent the minimal number of messages by filtering contact before getting chuncks of 3 (rather than the other way)
- fix a …
=> Fix various closed group

js/modules/loki_snode_api.js
This could get stuck in an infinite loop if we filter out all but one guard node from the database. The fix is to check if we have more than one, and select new guard nodes otherwise. For simplicity we throw away the one node, but (as future work) we probably want to keep it.
=> More robust guard node selection

tslint.json
This is a small lint fix which allows static methods which begin with lower case methods.
Before: `Class.DoSomething()`
After: `Class.doSomething()`
this is just a minor thing to allow stuff like `PubKey.from()`
=> Allow lowercase characters in static methods.

js/models/conversations.js, test/models/conversations_test.js, ts/session/messages/outgoing/content/TypingMessage.ts, ts/session/messages/outgoing/content/data/ExpirationTimerUpdateMessage.ts, ts/session/messages/outgoing/content/data/group/ClosedGroupMessage.ts, ts/session/messages/outgoing/content/data/index.ts, ts/session/protocols/MultiDeviceProtocol.ts, ts/session/sending/MessageQueue.ts, ts/session/sending/MessageQueueInterface.ts, ts/session/types/PubKey.ts, ts/test/session/messages/ClosedGroupChatMessage_test.ts, ts/test/session/messages/TypingMessage_test.ts, ts/test/session/protocols/SessionProtocol_test.ts, ts/test/session/sending/MessageQueue_test.ts
This PR updates `sendToGroup` to handle messages which have a `groupId` in them.
It also makes the `PubKey` constructor throw if invalid public key is passed which should help us in catching more errors.
=> Handle typing and expiration messages when sending to group

js/models/conversations.js, ts/receiver/groups.ts
This fixes an issue where `REQUEST_INFO` is continuously sent back and forth between paired devices after leaving a group.
=> Fix closed group infinite request loop

js/models/conversations.js, ts/components/conversation/TimerNotification.tsx, ts/session/messages/outgoing/content/data/ExpirationTimerUpdateMessage.ts
We forgot to assign the group id to the message.
Also
```
message.set({ destination: this.id });
```
we do this because sync messages use `destination` when sending and it was `undefined` in groups. I figured there's no harm setting it even on groups since it doesn't seem to be used anywhere else.
=> Fix expire timer not working in closed group

js/background.js, js/models/conversations.js, js/models/messages.js, ts/components/session/SessionGroupSettings.tsx, ts/receiver/dataMessage.ts, ts/receiver/queuedJob.ts, ts/session/messages/outgoing/content/data/group/ClosedGroupUpdateMessage.ts, ts/session/protocols/SessionProtocol.ts, ts/session/utils/Protobuf.ts
* fix display name and avatar to be shown when message is coming from a secondary device
* fix show of expiretimer in the group conversation when it is for it.
* fix a bug creating empty conversation when sync closed group message is received on secondary device
* trigger an expiretimer update message to all members when updating a group.
* trigger an expiretimer update message when sending back group details (after a requestGroupInfo)
=> Various closed group fixes

ts/session/sending/MessageSender.ts
session v1.0.9 and before expects a `path` and `verb` to be set on websocket message, so include them so recent session versions are able to speak to one another.
=> include verb and path on outgoing websocket message

ts/components/session/SessionClosableOverlay.tsx
fix our current device being shown when creating a closed group (if we have a note to self conversation)
=> hide ourdevices when creating a closed group

js/background.js, ts/session/messages/outgoing/content/data/group/ClosedGroupUpdateMessage.ts
building ClosedGroupUpdate message via ts makes it have an avatar
content with fields empty if we pass '' as avatar.
we want no avatar field at all
=> fix empty avatar being undefined rather than ''

Gruntfile.js, js/models/messages.js, js/modules/loki_message_api.js, js/modules/metadata/SecretSessionCipher.js, js/signal_protocol_store.js, libloki/api.js, libloki/test/index.html, libtextsecure/errors.js, libtextsecure/index.d.ts, libtextsecure/outgoing_message.js, ts/session/snode_api/serviceNodeAPI.ts, ts/test/types/Conversation_test.ts, ts/types/Message.ts
Fix our handling of snode sending errors so we have a real error when a message fails to send because of it.
Also, fix the retry logic on the corresponding message from the ui. Fetch our conversation directly to call `getOurProfile()`
=> Fix sending errors handling

js/models/conversations.js
Do not send an expireTimer message if the message timer is not set when a group is added to a closed group
=> Fix expire timer

js/modules/loki_app_dot_net_api.js
If we get a 403 back from any polling, it's likely our token is invalid (possibly due to memory driver, deletion/data lost, expiration, etc)
=> better detect when token is no longer valid (helps whitelist servers)

js/logging.js, password_preload.js
This PR fixes error logging in unhandled promise errors so that it prints out a stack trace.
This should help us in the future when tracking down weird errors.
=> Improve unhandled promise error logging

js/views/create_group_dialog_view.js, ts/receiver/contentMessage.ts
We block a message from a user in all cases except if:
* this message is a group message
* the group already exist in our db
* the group is not blocked
* the content of the message is control only
=> do not drop group control message from blocked user

ts/components/session/settings/SessionSettings.tsx
Fixes #1311 
It checks now for a Model. Because if I Block a User and then delete his Contact. The Blocked Session ID is stored but the model for that contact not.
=> Check for model in blocked settings

stylesheets/_conversation.scss
Fix the size of the conversation panel. 
If the window was too small, sent messages were not visible, and the emoji panel was too big.
Needs https://github.com/loki-project/session-desktop/pull/1320 to be merged first. The only interesting commit is the last one.
=> Fix emoji panel

app/sql.js, background.html, background_test.html, js/background.js, js/models/conversations.js, js/models/messages.js, js/modules/data.d.ts, js/modules/data.js, js/modules/loki_app_dot_net_api.d.ts, js/modules/loki_app_dot_net_api.js, js/modules/loki_message_api.js, preload.js, stylesheets/_modules.scss, stylesheets/_session.scss, stylesheets/_theme_dark.scss, test/index.html, ts/components/conversation/Message.tsx, ts/receiver/dataMessage.ts, ts/receiver/multidevice.ts, ts/receiver/receiver.ts, ts/receiver/syncMessages.ts, ts/session/sending/MessageQueue.ts, ts/session/sending/MessageSender.ts, ts/test/session/unit/sending/MessageQueue_test.ts
Order messages received by the server created_at timestamp rather than the one included in the message.
This is to prevent messages from a user with an out of sync clock to be able to sent message way in the past or in the future.
Also changes the way we check for duplicates. As we now rely on the server timestamp, we have a difference of timestamp between the message we sent, and the message the server sent us back on pull. This creates two messages on desktop. The way to fix it is to add a timeframe of 10s during a which, a message from a specific user and with the same content will be considered a duplicate, and so will be dropped
=> Use created at server timestamp

app/tray_icon.js, js/views/conversation_view.js
Bug reported by Brice
* Enabling read-receipt setting would make a conversation open in the stack but not on foreground mark its message as read as they were coming in.
* the issue was the way we were checking for which conversation is in foreground or not.
=> Fix read setting marking read

js/models/messages.js, js/modules/loki_app_dot_net_api.js, js/modules/loki_push_notification_server_api.js, js/views/inbox_view.js, preload.js, ts/session/sending/MessageQueue.ts, ts/session/sending/MessageQueueInterface.ts, ts/session/sending/MessageSender.ts, ts/session/snode_api/onions.ts, ts/session/snode_api/serviceNodeAPI.ts
notify the PN server on message sent, so that it triggers a push notifications to mobile devices
=> add notify to PN server on message sent

js/views/conversation_view.js, js/views/create_group_dialog_view.js, ts/components/session/SessionGroupSettings.tsx, ts/receiver/groups.ts
Any member of a closed group can now update a group name or group members.
=> allow closed group updates from non-admin user

js/background.js
LokiAppDotNetServerAPI::findOrCreateChannel now takes 3 parameters, and open group invites call here wasn't updated.
Changed to use the more standard LokiPublicChatAPI::findOrCreateChannel
This fixes Open Group Invites
=> fix out dated parameters to findOrCreateChannel for open group invites

ts/receiver/mediumGroups.ts
This case can happen on restore from seed
=> Generate our own senderkey if it does not exist

CONTRIBUTING.md
Session requires like Signal vs2015 Windows Build tools for some reason.
So I added this info to the Contributing Guide to give more love to the Windows Dev Bois
=> Add --vs2015 to windows setup instructions

config/swarm-testing.json, js/modules/loki_app_dot_net_api.js, preload.js, ts/components/AvatarPlaceHolder/AvatarPlaceHolder.tsx, ts/session/snode_api/onions.ts, ts/window.d.ts
- Add `useOnionRequestsV2` feature flag (disabled by default) to use onion requests v2
- New encoding is as follows: `| <4 bytes little-endian> N | <N bytes> ciphertext | <utf8 encoded json> extra |` 
- `onions/v2` will be available on SS in the next hardfork
- Fileserver does not yet support v2 onions
=> Optionally use v2 onions for snode requests

js/modules/loki_app_dot_net_api.d.ts, ts/receiver/attachments.ts
File uploads in open groups live on their own fileserver. While we were uploading to the right server, when downloading we always used file.getsession.org. Ideally each attachment should remember which server/API it belongs to, but all we have right now it the url (which might be mangled: uploading to `file.getsession.org` might procude an attachment with url `file-static.getsession.org`...). Current this PR adds a workaround that tries to connect to the right server based on that url.
=> Fix open group file uploads using incorrect server

js/models/conversations.d.ts, js/models/conversations.js, js/signal_protocol_store.js, js/views/conversation_view.js, libtextsecure/errors.js, libtextsecure/index.d.ts, ts/components/session/conversation/SessionConversation.tsx, ts/receiver/contentMessage.ts, ts/receiver/dataMessage.ts, ts/receiver/sessionHandling.ts, ts/session/messages/outgoing/content/SessionRequestMessage.ts
Fix the restoring from seed when one of the coming message is a prekey.
BEFORE RESTORING FROM SEED
""""""""""""""""""""""""""
B sends to A some messages, triggering the creation of a preKeyBundle of ID lets say 1.
B sends this preKeyBundle as a SESSION_REQUEST message
B stores this preKeyBundle and waits for A to reply for a SESSION_CREATED message.
When B gets that message (it can be any message not encoded with prekey), B removes this prekey from it's database.
At this point A and B can communicate.
'A' RESTORES FROM SEED
""""""""""""""""""""""
When A restores from seed he gets the preKeyBundle of ID 1, again. (if less than the time it is stored on snodes.)
But B, already burnt that preKeyBundle.
A thinks he is creating a working session with B but he is not.
As long as B does not tell …
=> fix restoring of session after restore from seed

ts/components/session/conversation/SessionCompositionBox.tsx, ts/components/session/conversation/SessionRecording.tsx, ts/state/ducks/SessionTheme.tsx, ts/styled.d.ts
Fixes a few issues related to the playback on the Composition view
* check of media permissions on click rather than on mount
* no opacity for the playback canvas color. having an opacity was causing issues with the source-atop composition of the sweeping timeline
=> Fix recording view

.github/workflows/build-binaries.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, package.json
force ubuntu-18.04 for github actions
building on ubuntu 20.04 was causing issue with a too recent glibc for
some users dependent on ubuntu 18.04 or similar (elementary OS)
The issue arise as github action ubuntu-latest was upgraded recently too
ubuntu 20.04.
This fix forces the app to be built on ubuntu 18.04
=> force ubuntu 18.04 for workflows (issue with glibc being too recent)

app/sql.js, js/modules/data.d.ts, js/modules/data.js, libloki/crypto.d.ts, libloki/crypto.js, protos/SignalService.proto, ts/receiver/cache.ts, ts/receiver/closedGroups.ts, ts/receiver/contentMessage.ts, ts/receiver/keyPairRequestManager.ts, ts/receiver/receiver.ts, ts/session/group/index.ts, ts/session/messages/outgoing/content/data/group/ClosedGroupEncryptionPairMessage.ts, ts/session/messages/outgoing/content/data/group/ClosedGroupEncryptionPairReplyMessage.ts, ts/session/messages/outgoing/content/data/group/ClosedGroupEncryptionPairRequestMessage.ts, ts/session/messages/outgoing/content/data/group/index.ts, ts/session/sending/MessageQueue.ts, ts/session/sending/MessageQueueInterface.ts, ts/session/utils/Messages.ts, ts/test/session/unit/messages/ConfigurationMessage_test.ts, ts/test/session/unit/receiving/ConfigurationMessage_test.ts, ts/test/session/unit/receiving/KeyPairRequestManager_test.ts, ts/test/session/unit/sending/MessageQueue_test.ts, ts/test/session/unit/utils/Messages_test.ts, ts/test/test-utils/utils/envelope.ts
Fixed the closed group logic 
[x] Be able to request an keypair if we somehow lost it but are still a member of the group.
[x] only handle the first configuration message incoming
[x] self-send closed group updates of type new
=> add the request and reply of an encryptionKeyPair if needed

js/modules/loki_app_dot_net_api.js
This fixes open groups to be able to get a token when onion requests fail.
submit_challenge API returns a 200 with no text, so the JSON.parse would fail (even though noJson option was set)
Also cleans up the logging output a bit to be useful.
=> Replace unused textResponse with used noJson, updating logging

_locales/ja/messages.json
This, along with https://github.com/oxen-io/session-android/pull/470, is my first set of contributions to Japanese translation.
My aims:
- Improve comprehensibility and correctness of Japanese translations.
- Make Japanese translations consistent within and across Session repos.
Please refer to each commit message for details.
=> Initial fixes to Japanese translations

ts/components/session/conversation/SessionConversation.tsx, ts/session/conversations/ConversationController.ts
also, removing a private convo does not remove it entirely as we need
the convo to be able to remove members
=> create convo for members if they don't exist

_locales/ja/messages.json
Translations of some strings that I found were untranslated in the GUI and some in the Japanese strings file, some improvements on existing strings.
`_locales/ja/messages.json:1106: "ByUsingThisService..."`
By the way the terms of use and privacy policy are presented and the implied consent, there is a risk the terms of use and privacy policy may not legally apply to users in Japan. https://topcourt-law.com/terms_of_service/how-to-get-consent
=> More Japanese translations

ts/components/ConversationListItem.tsx
No longer shows the (...pubkey) text for a conversation list items and contact list items.
=> Hiden shortened pubkey of message's author unless its an open group chat.

ts/pushnotification/PnServer.ts, ts/session/snode_api/onions.ts
the dev pn server is not used in the app, this change is just here to
not have to think of switching this part too when debugging against the
pn dev server
=> add pn server dev url fallback to v2/lsrpc

js/background.js, ts/components/session/conversation/SessionCompositionBox.tsx, ts/components/session/settings/SessionSettings.tsx, ts/data/data.ts, ts/window.d.ts
Fix for #1756 
Display the link preview popup only once
=> Display link preview popup only once

stylesheets/_modules.scss, stylesheets/_session_theme.scss, stylesheets/_theme_dark.scss, ts/components/conversation/Message.tsx
Outgoing/incoming image attachment messages no longer have a background so the image transparency reaches the conversation screen. Changed the background of the parent element for the example. Aqua message showing white is a jpg without transparency.
=> Transparent pngs

ts/components/session/conversation/SessionRightPanel.tsx, ts/models/conversation.ts
Fix for the issues:
- Add members and edit name buttons weren't displayed in groups
- isAdmin function in conversation.ts was always returning false for closed groups
=> Fix for name change and adding members in groups

_locales/en/messages.json, _locales/fr/messages.json, ts/components/conversation/MessageContextMenu.tsx, ts/interactions/messageInteractions.ts, ts/opengroup/opengroupV2/OpenGroupAPIV2.ts
Moderators in public groups can now ban an user and delete all his messages in a single action
=> 'Ban user and delete all messages' added to menu

ts/components/dialog/OnionStatusPathDialog.tsx
This change adds each service node's IP address to the onion path window. I personally find this information useful to check the networks of the nodes I am being routed through, and I think other users will enjoy having the extra information, too.
I have tested that the change works as described.
=> Display the service node's IP address after its country.

app/logging.js, ts/components/conversation/message/OutgoingMessageStatus.tsx, ts/components/session/conversation/SessionCompositionBox.tsx, ts/components/session/icon/SessionIconButton.tsx, ts/interactions/conversations/unsendingInteractions.ts
=> Fix close emoji click button

ts/components/session/conversation/SessionMessagesList.tsx, ts/components/session/conversation/SessionMessagesListContainer.tsx
[End] will scroll to the end of the current conversation, because the
latest message is always available.
[Home], however, will scroll only to the top of the currently loaded
messages, triggering earlier messages to load. Multiple presses of
[Home] are therefore required to get to the start of the conversation.
I wanted to implement [Home] such that it would continuously reload earlier messages until it reached the start of the conversation, but I couldn't get it to work. This is therefore a compromise, sending the user to the earliest message currently available and triggering the loading of even earlier messages, if available.
=> Make the [Home] and [End] keys scroll the conversation.

package.json, ts/receiver/callMessage.ts, yarn.lock
on archlinux, the appimage links to the system sqlite by default which
does not support sqlcipher
=> fix archlinux pw unused issue

ts/components/session/LeftPaneMessageSection.tsx, ts/opengroup/utils/OpenGroupUtils.ts
Currently the desktop Session high-level GUI silently refuses (i.e. just doesn't do anything, without feedback) some URLs it should allow, and accepts some invalid URLs it should refuse.
This updates the regex to fix the acceptance criteria, and adds an displayed error message when an invalid URL is entered.
---
Details:
- Add an error popup when the URL is rejected for being invalid.
- Capital letters in room tokens were not being accepted (it eventually gets lower-cased internally, which works fine, but that happens *after* the URL is tested for acceptability).
- `-` in room was not being allowed (it is and always has been on SOGS, session-android, and session-ios).
- one-letter rooms weren't being allowed (but are valid).
- complete URL regex wasn't anchored so something like …
=> Open group regex fixes

ts/components/avatar/AvatarPlaceHolder/AvatarPlaceHolder.tsx, ts/util/getInitials.ts
Use up to two scaled initials as a placeholder for users with no avatar.
If the user's name consists of just a single word, then use up to two letters from that word as the placeholder.
This provides better differentiation of users than the current practice of using just a single letter for everyone.
There's enough space in the avatar placeholder circle to place up to three scaled initials, which provides better user differentiation than a single letter.
@KeeJef considered the use of three initials excessive, so this has been reduced to a maximum of two. The screenshot below illustrates one-, two- and three-letter placeholder values.
Tested on Linux and Windows.
=> Use up to two scaled placeholder characters for users with no avatar.

ts/components/registration/RegistrationStages.tsx
See https://github.com/oxen-io/session-android/blob/master/libsession/src/main/java/org/session/libsession/utilities/SSKEnvironment.kt#L29
Desktop is inconsistent with Android. It allows user names of up to 20 characters, whereas Android allows up to 26 characters.
This brings desktop in line with Android.
My binary OCD would prefer 32. I mean, why 26?
Fixes #2206.
Tested on Linux and Windows.
=> Allow user names up to 26 characters long, in line with Android.

ts/session/utils/syncUtils.ts
This changed in  55253125428f1cc72d86f833b7ffca265e2feb84, way back in May 2021. It looks as if the comment wasn't updated in line with the change.
However, shouldn't a configuration sync occur more often than once a week? If so, this PR changes it back.
Alternatively, I can submit a PR to fix the comment.
=> Make configuration sync every 2 days, in line with the comment.

ts/components/leftpane/MessageRequestsBanner.tsx
This harmonises the styles of both unread counters in the left pane, following the recent acceptance of my patch to change the style of the per conversation unread message counter.
=> Style message request counter as per conversation message count.

stylesheets/_session_conversation.scss
This improves legibility for moderators when reading through a group and
tagging messages for deletion.
Once the user tags a message for deletion, it becomes hard to read the other messages as one scrolls through the group, yet this is the most efficient workflow for a moderator.
This patch renders unselected messages less dark and therefore more legible,
=> Reduce untagged message opacity during message selection.

ts/interactions/conversations/unsendingInteractions.ts
The count was being filled when the user did a `Delete for everyone`, but not when doing a `Delete only for me`.
=> Fix unfilled variable when user deletes messages only for himself.

_locales/en/messages.json, ts/interactions/conversations/unsendingInteractions.ts, ts/session/utils/Toast.tsx
This minor improvement reports the number of messages that were deleted when the operation completes.
=> Report number of deletions when a deletion operation completes.

.gitignore
We need to ignore the generated .parcel-cache folder since it builds every time we run `yarn grunt`. Tested on macOS.
=> fix: added .parcel-cache to gitignore

stylesheets/_session_conversation.scss, ts/components/conversation/SessionEmojiPanel.tsx
Fixed emoji panel colors when using the light theme. Have tested swapping between themes on macOS.
=> fix: emoji panel light mode support

ts/util/privacy.ts
I frequently find myself needing to patch out the redaction code in order to see where something is going wrong.
This patch applies no redaction to devprod builds, which seems entirely safe to me.
=> To aid debugging, don't redact strings when building for devprod.

stylesheets/_session.scss
When we have long messages with a link, the link wraps below the text and causes a large amount of white space. It would be better for the link text to wrap around.
Before:
After:
=> fix: message text should wrap without causing extremely wide messages

.gitignore, .prettierignore, .sassrc.json, Gruntfile.js, about.html, background.html, debug_log.html, package.json, password.html, stylesheets/_debugLog.scss, stylesheets/_emoji.scss, stylesheets/_session_conversation.scss, stylesheets/_variables.scss, stylesheets/manifest.scss, yarn.lock
- SASS complication now relies on Parcel and has been removed from Grunt. This allows us to drop a few dependencies. The SASS build times are also much faster. The compiled CSS is now stored in the `dist/` folder in the root of the project.
- Added the `sass:watch` npm script command for autocompiling the sass on file changes
- cleaned up some IE7 fallback CSS
=> feat: build sass files using parcel instead of grunt

stylesheets/_session.scss
Further fixes for #2336 see comment https://github.com/oxen-io/session-desktop/pull/2336#issuecomment-1132599207
=> fix: make sure to break links and not words when wrapping text in messages

ts/node/global_errors.ts
The ElectronJS error dialog box has a button that copies the error to the clipboard. Right now it quits the app automatically when it's clicked. This is undesirable since we can't access the entire log file or debug the state using the Inspector Tools. 
This change only closes the dialog when the option is selected and doesn't quit the app. The user must explicitly choose the 'Quit' button to close the app after an error occurs.
=> fix: global error dialog box's 'copy to clipboard' option shouldn't quit the app

patches/bunyan+1.8.15.patch
[bunyan](https://www.npmjs.com/package/bunyan) doesnt check if the filepath exists before running the finish command after a log rotation, I've patched it to create the directory if it doesn't exist yet
Should fix https://github.com/oxen-io/session-desktop/issues/2278 and https://github.com/oxen-io/session-desktop/issues/2333
Tested on macOS, Ubuntu and Windows
=> fix: handle missing logs folder when performing log rotations

ts/mains/main_node.ts
The icon is missing on linux so appImages run with a blank icon in the toolbar. This adds the icon member to electrons `BrowserWindow` config for the linux platform only and should correctly display icons in the toolbar now.
=> configure desktop icon for linux appImages

ts/receiver/contentMessage.ts, ts/session/messages/outgoing/controlMessage/DataExtractionNotificationMessage.ts
Make sure the "media saved" notification is not sent/handled if the read receipt settings is disabled
=> fixing the saved media read receipt

ts/components/conversation/composition/CompositionBox.tsx, ts/components/conversation/message/message-content/MessageText.tsx
Session allows a message to be composed and sent with leading and/or trailing whitespace. It will also display any leading and/or trailing whitespace in messages it receives.
This patch fixes both problems. Newly composed messages will be trimmed before sending, as will incoming messages before they are displayed.
Untidy messages such as the following are no longer possible:
=> Trim leading and trailing whitespace on message composition and display.

ts/node/sql.ts, ts/session/apis/open_group_api/opengroupV2/OpenGroupServerPoller.ts, ts/session/onions/onionSend.ts
the app was crashing if a convo with an invalid read/write/upload capability was saved during a migration
=> fix: make sure existing sogs convo do not break on save

ts/models/message.ts
this is to make those media visible on the right panel.
This only happens for attachments we are sending
=> fix: mark message as having attachmnents once data is uploaded

ts/models/conversation.ts
This can happen if the attachment is still downloading, or could not be
downloaded. The message will have attachments or thumbnails, without
valid data associated to it.
This fix makes sure we don't try to load invalid paths when trying to
gather the attachments and previews
=> fix: skip attachment without path when replying to a message

ts/components/conversation/message/reactions/Reaction.tsx
This is pretty nuanced, but when we have flex nowrap the descendants can be squished so we have to force no wrapping.
=> fix: Fixed Reaction text alignment in the React List modal

ts/models/conversation.ts, ts/session/apis/open_group_api/opengroupV2/JoinOpenGroupV2.ts, ts/session/apis/open_group_api/opengroupV2/OpenGroupManagerV2.ts, ts/session/apis/open_group_api/sogsv3/sogsApiV3.ts, ts/state/selectors/conversations.ts
also use the pollinfo to update whatever the displayname if needed
=> fix: show sogs without display name in convo list

ts/components/conversation/message/message-content/MessageReactions.tsx, ts/components/dialog/ReactListModal.tsx
- Prevent message reactions wrapping when in a compressed state.
Before:
After:
- When message reactions are expanded we will show a maximum of 10 emojis in a row.
Before:
After:
- Fix alignment of complex emojis in the React List Modal
=> Hotfix Message Reactions Width

_locales/en/messages.json
The left panel is currently titled *Messages*, but it contains conversations, not messages. The panel to its right contains messages.
Logically, the left panel should be titled *Conversations*. This patch makes the change.
=> Retitle left panel 'Conversations', since that's what it displays.

package.json
Currently the deb gets created with `Section: default` in the metadata, which isn't a valid debian section at all; this fixes it to be `net` to properly categorize it in deb package managers.
=> Fix .deb Section

package.json, yarn.lock
still 2 moderate issues but they are linked to our electron version, which will be more work than just upgrading those dependencies.
Fixes #2322
```
yarn audit 
yarn audit v1.22.19
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Exfiltration of hashed SMB credentials on Windows via        │
│               │ file:// redirect                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ electron                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=18.3.7                                                     │ …
```
=> chore: fix high and critical `yarn audit` issues

stylesheets/_global.scss, stylesheets/_session.scss, stylesheets/_session_constants.scss, stylesheets/_session_signin.scss, stylesheets/_session_theme.scss, ts/components/leftpane/LeftPaneSettingSection.tsx, ts/components/leftpane/overlay/OverlayClosedGroup.tsx, ts/themes/globals.tsx
=> Fix cyrillic font

background.html, password.html, ts/components/SessionContextMenuContainer.tsx, ts/components/button/MenuButton.tsx, ts/models/messageType.ts, ts/node/sql.ts, ts/session/apis/open_group_api/sogsv3/sogsApiV3.ts, ts/session/apis/snode_api/getSwarmFor.ts, ts/session/apis/snode_api/swarmPolling.ts, ts/session/group/closed-group.ts, ts/session/messages/outgoing/visibleMessage/VisibleMessage.ts, ts/session/sending/MessageQueue.ts, ts/session/utils/libsession/libsession_utils_contacts.ts
this comes from mdplusplus https://github.com/mdPlusPlus/session-desktop/tree/codespell
duplicated to fix conflicts
from @mdPlusPlus https://github.com/oxen-io/session-desktop/pull/2816
`codespell --skip=_locales,*.lock -L keypair,keypairs,ons,usera,readby,falsy -w -i 3`
=> chore: fix typos

package.json, stylesheets/manifest.scss, ts/components/SessionContextMenuContainer.tsx, ts/components/calling/CallButtons.tsx, ts/components/conversation/message/message-content/MessageContextMenu.tsx, ts/components/conversation/message/message-item/GenericReadableMessage.tsx, ts/components/menu/ConversationHeaderMenu.tsx, ts/components/menu/ConversationListItemContextMenu.tsx, ts/components/menu/MessageRequestBannerContextMenu.tsx, yarn.lock
=> Fix attachment right click save as

README.md
Corrects a stale link in the URL to Kee's key.
=> Fix KeeJef gpg pubkey link

package.json, yarn.lock
Relates CVE-2023-4863
Relates #2922
electron backported the fix to 25.8.1: https://releases.electronjs.org/release/v25.8.1
=> chore: update electron to v25.8.1

CONTRIBUTING.md
Let users know that they need to run the Python script after they add new strings to messages.json. Pretty sure this is something i needed to run when adding strings.
=> docs: update I18n section

_locales/en/messages.json, ts/state/ducks/search.ts, ts/types/LocalizerKeys.ts, ts/types/Search.ts
Mainly useful for people who are swapping between different messengers, some messengers (Telegram) use the term "Saved messages"
=> feat: Allow to find "Note to Self" conversation with "saved messages"

stylesheets/_modules.scss, ts/components/leftpane/MessageRequestsBanner.tsx
This PR fixes unread message bubbles in message requests, so that they use the same colors as unread message bubbles for conversation items, previously they were deviating. See below
This is now fixed as such 
it also vertically aligns all conversation header items, so that author name, unread count and date are inline
=> Update unread message theming and alignment 

ts/components/conversation/message/message-content/MessageBody.tsx
Made it so mentions are rendered in private chats. While they are disabled on private chats, if you send manually @<the full pk> it now replaces the full pk with the nickname/name/You of the mentioned user.
=> Fix: render mentions in private chat message body

ts/components/dialog/SessionSeedModal.tsx
Fixes an issue with the visibility of the recovery phrase
=> Fix: enforce password check before modal view for recovery phrase

ts/components/conversation/message/message-content/MessageReactions.tsx
Changed the message reaction container margin to use the avatar list width
=> Fix: change reaction container to use group avatar list margin width

stylesheets/_modules.scss, ts/components/conversation/message/message-content/MessageAttachment.tsx
Opening this for conversation, this changes the whole attachment message to be clickable, instead of just the file icon, this brings Session inline with Telegram and i think is more intuitive.
=> Make whole attachment area clickable

ts/components/SessionScrollButton.tsx, ts/components/conversation/SessionMessagesListContainer.tsx, ts/components/icon/SessionIcon.tsx, ts/components/icon/SessionIconButton.tsx, ts/components/icon/SessionNotificationCount.tsx, ts/components/leftpane/conversation-list-item/HeaderItem.tsx, ts/hooks/useParamSelector.ts, ts/session/constants.ts, ts/state/selectors/conversations.ts, ts/state/selectors/selectedConversation.ts
Add a unread message count indicator per conversation, next to the read all message down arrow
Cherrypicks and rebases this feature from #2693
=> Add unread message count indicator per conversation

ts/components/settings/SessionNotificationGroupSettings.tsx, ts/components/settings/SessionSettings.tsx, ts/components/settings/section/CategoryAppearance.tsx, ts/components/settings/section/CategoryHelp.tsx, ts/components/settings/section/CategoryPermissions.tsx, ts/components/settings/section/CategoryPrivacy.tsx
Relates https://github.com/oxen-io/session-desktop/pull/2954 https://github.com/oxen-io/session-desktop/issues/1768
=> feat: dont password protect the settings except the seed one

ts/session/constants.ts, ts/util/attachmentsUtil.ts
Before:
[Screencast from 2024-05-02 11-21-59.webm](https://github.com/oxen-io/session-desktop/assets/5667907/d4d0d333-3d20-44a0-ad4b-7512096da13d)
After:
Also change the max avatar file size to 5MB to be in line with IOS and Android.
=> Change max avatar size to match other platforms

ts/components/conversation/Timestamp.tsx, ts/components/leftpane/overlay/OverlayClosedGroup.tsx, ts/receiver/configMessage.ts, ts/session/constants.ts
If a group is missing a `joinedAt` value we use fallback value so we can poll for it and display it in the conversation list
=> Restoring an account should restore all groups

package.json
release branches are now protected so we should bump the version on `unstable` before creating the release branch
=> chore: update package.json version to 1.13.2
