libtextsecure/account_manager.js

…skip sending keys to server.
- Replace phone number with PubKey
- Skip generating all keys and passwords that we won't use
- Skip saving keys on server

Replace phone number with pubkey as identity.

---

background.html
js/background.js
js/views/standalone_registration_view.js
main.js

- Force "standalone device" mode, instead of "link your phone"
- Removed SMS request and validation from UI
- Hide options to switch mode in the menu (includeSetup)

Bypass SMS verification

---

README.md

Change Signal readme

---

libtextsecure/outgoing_message.js

Wrap outgoing message in a WebSocketMessage proto object to match incoming format.
To do: The outgoing message encoding needs to be changed from json/string to binary.

Reconcile incoming and outgoing messages

---

background.html
js/background.js
js/views/app_view.js
js/views/confirmation_dialog_view.js
libtextsecure/message_receiver.js

- display a modal to the user for accepting or declining a friend request (Using the existing `ConfirmationDialogView` class until we have a proper UI guide)
- send an empty message back with our own prekeys upon accepting the friend request

Friend request prompt

---

background.html
js/views/standalone_registration_view.js
libloki/mnemonic.js
libtextsecure/account_manager.js

The mnemonic code handles multiple language word lists, so this PR exposes these languages to the user as a dropdown list.

Add Mnemonic language dropdown

---

config/default.json
js/modules/loki_message_api.js

Hope you like how this one turned out, really pushed me to my limits
Gonna take a well deserved break after slugging through this goliath

Tiny url update to work with the storage server

---

libtextsecure/outgoing_message.js

Current behaviour:
After sending friend request message, the editor is locked only after the message was successfully sent (HTTP response 200ish). But with the proof of work, there is a time window where more messages could be queued before the first request is actually sent.
Desired behaviour:
Lock the editor straight away after sending the friend request. Then unlock it upon failure of sending the message.

Always lock editor after sending friend request. unlock if error.

---

js/views/conversation_search_view.js

This fixes the issue where users are able to start a new conversation with someone even if they already have an existing conversation in place.

[Fix] User searching

---

js/models/conversations.js
js/views/conversation_search_view.js
test/models/conversations_test.js
test/views/conversation_search_view_test.js

This PR allows us to show the user when they have typed in an invalid public key.
A public key is valid if:
- It is a hex string
- it has a length of 66 characters. (33 * 2)
- though i'm not sure if this is right or not 🤔 
I also went ahead and updated tests and removed code which used phone numbers.

Public key validation

---

config/development2.json
main.js

First terminal:
`yarn start`
Second terminal:
```
export NODE_ENV=development2
yarn start
```
Boom!

Allow multiple instances running for debugging

---

js/modules/loki_message_api.js
libloki/libloki-protocol.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
preload.js

ES2015 classes for LokiServer and FallBackSessionCipher

---

js/models/conversations.js
js/modules/data.js
js/views/app_view.js
libtextsecure/message_receiver.js

This PR fixes duplicate friend requests being received.
This also fixes saving preKeys when another user accepts the friend request.
**NOTE: After friend request is accepted, any subsequent message successfully sends, however on the receivers end it errors out while unpacking from protobuf**

[Pending] Fix duplicate messages

---

libtextsecure/http-resources.js
libtextsecure/message_receiver.js

The connectivity logic is still relying on the websocket to determine if we have connectivity issues.
This PR makes it possible to get the status from the HTTP polling resource.
Additionally, we need to call `onEmpty` to emulate the Signal behaviour.
With Signal, the websocket server would send 'empty' requests as a form a keep-alive.
This is used internally to know if we everything is still good, but also is a trigger for the loading screen to disappear once the app is ready.
I also have removed the early return in message_receiver::connect, and replaced it with a `if (useWebSocket)` because I needed the last statement in that function.
(if we don't have internet connectivity at all, then a fake `empty` event is triggered in inbox_view.js l:219 to get past the loading screen).

Make network status warning work with HTTP polling

---

_locales/en/messages.json
js/models/conversations.js
js/models/messages.js
libtextsecure/message_receiver.js

This PR adds notifications for friend requests.

Friend Notifications

---

app/sql.js
js/background.js

This was an uncaught bug in the other PR.

Fix incoming messages being deleted on startup.

---

app/sql.js
js/background.js
js/modules/data.js
libtextsecure/http-resources.js

Now storing the hashes of all incoming messages in a new table
Before trying to decrypt any incoming messages the message hashes are tested against this table and ignored if they have already been seen
On application start and every hour when running the table has all the expired messages removed
Message expiration now being sent by the storage server

Filtering incoming messages

---

protos/SignalService.proto

add PrekeyBundle Type field in SignalService.proto

---

_locales/en/messages.json
js/background.js
js/settings_start.js
js/views/settings_view.js
main.js
preload.js
settings.html
settings_preload.js

Added read receipt checkbox to the settings window which enables or disables the sending and receiving of read receipts

Read receipts setting

---

libtextsecure/outgoing_message.js

Fix inexistent enum value for Prekey Type

---

js/models/conversations.js

remove `isFriend` from conversation default

---

js/modules/loki_message_api.js
libloki/proof-of-work.js
libtextsecure/http-resources.js
libtextsecure/message_receiver.js

Quality of life changes for us, paired with service-node-storage PR

Removed some repetetive logs, developer mode settings

---

_locales/en/messages.json
background.html
js/background.js
js/conversation_controller.js
js/models/conversations.js
js/models/profile.js
js/modules/signal.js
js/modules/types/contact.js
js/views/app_view.js
js/views/conversation_view.js
js/views/inbox_view.js
js/views/nickname_dialog_view.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js
protos/SignalService.proto
stylesheets/_conversation.scss
stylesheets/_index.scss
stylesheets/_modules.scss
stylesheets/_theme_dark.scss
test/index.html
ts/components/IdentityKeyHeader.tsx
ts/components/conversation/ContactName.tsx
ts/components/conversation/ConversationHeader.tsx

This PR allows users to set their names which will be shared automatically to all other users.
Users can also set a nickname to a contact.

Added profile sharing and setting nicknames.

---

js/modules/data.js
js/signal_protocol_store.js

More log level finetuning

---

_locales/en/messages.json
background.html
js/views/standalone_registration_view.js
libtextsecure/account_manager.js
stylesheets/_conversation.scss
stylesheets/_global.scss
stylesheets/_modules.scss
stylesheets/_variables.scss
ts/components/conversation/ConversationHeader.tsx

This PR updates the UI of the registration screen.

Registration UI

---

background.html
js/views/inbox_view.js
js/views/standalone_registration_view.js
stylesheets/_index.scss

Added unread indicator in conversation section.

---

libloki/libloki-protocol.js
libloki/test/libloki-protocol_test.js

signedKeyId needs to be initialised to 2 in the test.
Also, fixed the default value in loki-protocol.

fix loki test

---

CONTRIBUTING.md

Should probably have done this a while ago lol

Update CONTRIBUTING.md to reflect loki-messenger

---

_locales/en/messages.json
background.html
js/background.js
js/views/app_view.js
js/views/inbox_view.js
js/views/seed_dialog_view.js
js/views/standalone_registration_view.js
libloki/mnemonic.js
libtextsecure/account_manager.js
stylesheets/_conversation.scss
test/index.html

This PR allows the ability for the user to view their seed.
**Note:** We store the seed in the database, so anyone with access can view it. This shouldn't be an issue if users set a custom password on their db.
#90

Allow viewing seed

---

.travis.yml

Addresses #95 
A copy of the gitlab setup but it runs tests on PRs

Run tests on travis on pull requests.

---

main.js
stylesheets/_global.scss
stylesheets/_index.scss

Fixes an issue where the app quits after showing main window on linux.
Fixes css issues on linux.

Linux fixes

---

js/views/conversation_view.js
ts/components/conversation/ConversationHeader.tsx

Added option to copy conversation public key.

---

Gruntfile.js
js/views/conversation_view.js

Added tsx files to grunt watch.
Fixed minor bug in conversation view.

Minor fixes

---

js/models/conversations.js
js/notifications.js

Fix notification display after friend request is accepted.

---

libloki/proof-of-work.js

This should resolve #108 for most devices.

Reduced PoW difficulty to 100 on production.

---

libloki/test/metrics.js
metrics.html

Allow to see the influence of TTL on PoW execution time

add TTL variation in pow metrics

---

js/conversation_controller.js
js/models/conversations.js
js/notifications.js

Fixes #134 
This also fixes a minor notification bug that i missed.

Fix contact display

---

app/user_config.js

Trivial change of folder name for app path in development mode.

Changed development folder to 'Loki-Messenger-Development`

---

js/modules/loki_message_api.js

In js, the `in` operator works only for keys in objects (does work in python tho I think, confusing!)

Fix sending loop that cycles indefinitely when offline

---

js/conversation_controller.js
js/models/conversations.js
js/modules/data.js
js/modules/loki_p2p_api.js
js/views/conversation_list_item_view.js
stylesheets/_modules.scss
test/backup_test.js
ts/components/Avatar.tsx
ts/components/ConversationListItem.tsx

I couldn't really test this since lokinet doesn't work on Mac at the moment.
Currently this is only shown on the left menu, do we want to show them on the conversation header as well?

Online indicator

---

js/modules/loki_p2p_api.js
libtextsecure/message_receiver.js

Some more sensible function/variable names plus fixed and simplified some logic for the handling of loki address messages
(Previously certain flows would result in waiting for a ping timer before a user would get marked as online)
Fixes #166

P2p logic fixes

---

js/models/conversations.js
js/views/conversation_view.js
ts/components/Avatar.tsx
ts/components/ConversationListItem.tsx
ts/components/conversation/ConversationHeader.tsx
ts/types/Util.ts

Added online indicator to conversation header.

---

app/auto_update.js
js/views/conversation_view.js
libtextsecure/libsignal-protocol.js
libtextsecure/sendmessage.js
main.js
package.json

Mainly small bugfixes coming from textsecure.

Merge 1.21.1

---

CONTRIBUTING.md

Noticed this when going through installation on a new linux VM from scratch.

Update contributing.md for hunspell on linux

---

js/models/conversations.js

Clear timers after friend request complete and don't do timer related things if we are already friends
Fixes #200

Fix friend request timer bug

---

bower.json
components/multibase/dist/index.js
libloki/crypto.js
libloki/test/index.html
libloki/test/snode_channel_test.js
yarn.lock

Linted and tested.
Not in used so far, will be hooked up after #197.
Contributes to #174

Add channel encryption library with tests 

---

js/modules/loki_message_api.js
libloki/modules/local_loki_server.js

Cleans up the code a bit in loki messenger api

Refactor rpc call to its own function.

---

js/views/settings_view.js
preload.js

Made the slider label populate as well, plus removed redundant window function
Completes #223

Fix ttl slider

---

js/modules/loki_snode_api.js
libtextsecure/errors.js
libtextsecure/message_receiver.js

Catch errors when starting local server and retry every 30 seconds
Completes #224 
Completes #211

Retry p2p server if failed to start

---

_locales/en/messages.json
app/menu.js
main.js
test/app/fixtures/menu-mac-os-setup.json
test/app/fixtures/menu-mac-os.json
test/app/fixtures/menu-windows-linux-setup.json
test/app/fixtures/menu-windows-linux.json
test/app/menu_test.js

Fix #214
Decided to remove the Forum stuff instead of commenting out.
If one day we need it back we can just revert partially this commit.
Tests and linting pass 👍

Replace help menu links

---

js/views/password_view.js

Added enter to log in

---

_locales/en/messages.json
js/background.js
js/conversation_controller.js
js/models/conversations.js
js/views/app_view.js
js/views/conversation_list_item_view.js
js/views/conversation_list_view.js
js/views/conversation_view.js
js/views/inbox_view.js
ts/components/ConversationListItem.tsx
ts/components/conversation/ConversationHeader.md
ts/components/conversation/ConversationHeader.tsx

Added ability to delete contacts and destroy all sessions with them
Added right click menu to contacts/conversations in list which can block, delete messages and delete contact
Completes #252

Delete contact + right click menu

---

js/conversation_controller.js

Allow conversation symbol to generate while swarm nodes are being retrieved

Fix bug with UI when creating conversation

---

libloki/modules/local_loki_server.js
libloki/test/node/local_loki_server_test.js
libtextsecure/http-resources.js
libtextsecure/message_receiver.js

Added success and failure callbacks when queueing envelope, now responding with 404 if we fail to decrypt a p2p message

Only respond 200 to successful p2p messages

---

js/modules/loki_message_api.js
js/modules/loki_snode_api.js
libloki/api.js
libtextsecure/errors.js

Cleaned up a lot of the logs, stop them from printing more than once etc
Might need some more cleaning later but want to get this in to get a better feel for them before making more changes

Improve sending/retrieving/swarm logs

---

app/password_util.js
background.html
js/views/standalone_registration_view.js
stylesheets/_global.scss

Resolves #232 
Resolves #220 
First screen:
Second screen:

Changed registration to be a 2 step process.

---

js/modules/loki_rpc.js

Much more simple than I thought

Disable encryption

---

js/modules/loki_message_api.js
libloki/proof-of-work.js
libloki/test/metrics.js
libloki/test/proof-of-work_test.js
libtextsecure/outgoing_message.js

Multiple all ttl values by 1000 and stop dividing timestamp by 1000 so they are both milliseconds

Ttl and timestamp milliseconds

---

CONTRIBUTING.md
bower.json
debug_log.html
fix_broken_perms.sh
js/modules/debuglogs.js
test/modules/privacy_test.js

Replaced more references to signal with loki and updated CONTRIBUTING.md

Remove Signal references

---

libtextsecure/outgoing_message.js

Been meaning to get rid of this for yonks

Remove old log

---

js/modules/loki_message_api.js
js/modules/loki_snode_api.js
libtextsecure/outgoing_message.js

Refactoring sendMessage in preparation for fixing #294 (restarting the sendMessage logic to try again with a new PoW)
Remove up old retrieveMessage function

Refactor sendmessage

---

config/default.json
js/background.js
js/modules/loki_message_api.js
js/modules/loki_rpc.js
js/util_worker_tasks.js
libloki/proof-of-work.js
libloki/test/metrics.js
libtextsecure/errors.js
main.js
preload.js

Clients now save their PoW difficulty (formerly NONCE_TRIALS in the storage) and can update it when informed to do so by service nodes
There's a bunch of simple renaming because I changed nonce_trials to difficulty and also cleaned up loki_rpc a bit
closes #291

Dynamic pow

---

js/util_worker_tasks.js
libloki/proof-of-work.js

Trial value wasn't being initialised big enough for very low difficulty, also development should not have been there but I don't think it was doing anything
Merging now to have clearnet messenger build ready tomorrow morning

Fix PoW for very low difficulty

---

js/models/conversations.js

Will need to conduct further testing once the clearnet is alive again but hopefully completes #303

Consider friend requests that are still being sent as sent

---

ts/components/conversation/ConversationHeader.tsx

Comment out the show all media button

---

js/models/conversations.js
libtextsecure/account_manager.js

Initialise conversation with ourselves as friends and don't allow it to be changed to anything else

 Fix not to self

---

js/modules/loki_snode_api.js
libtextsecure/errors.js

Use get_n_service_nodes API
Remove random snodes if they fail and then try again.
Throw seed node error if getRandomSnodeAddress fails.
Filter out 0.0.0.0 nodes.
Closes #309 
Closes #310

Random list

---

js/modules/loki_rpc.js
libloki/modules/local_loki_server.js
libloki/test/node/local_loki_server_test.js

Storage server being updated to version every endpoint

Update endpoint for storage server and p2p

---

libloki/api.js

Prevents getting errors at startup.

Fix self broadcast

---

js/modules/loki_message_api.js
js/modules/loki_snode_api.js

Fix silly filtering bug, add filtering for swarm nodes and lint

---

js/background.js
js/modules/loki_snode_api.js
libloki/api.js
libloki/modules/local_loki_server.js
libloki/test/node/local_loki_server_test.js
libtextsecure/message_receiver.js
preload.js

We weren't actually removing bad nodes since we started using ips... whoops
Most of this diff is just running lint
The only new change is here
```diff
async unreachableNode(pubKey, nodeUrl) {
const conversation = ConversationController.get(pubKey);
const swarmNodes = [...conversation.get('swarmNodes')];
- const filteredNodes = swarmNodes.filter(node => node.address !== nodeUrl);
+ const filteredNodes = swarmNodes.filter(
+   node => node.address !== nodeUrl && node.ip !== nodeUrl
+ );
await conversation.updateSwarmNodes(filteredNodes);
}
```

Run lint and check for ip or address when removing unreachable nodes

---

app/sql.js
main.js
password_preload.js

Closes #330 
Latest upstream merge broke the database password setup
Added a simple config check to determine if we should show the password window, and add a field to the database initialise to throw errors if we are trying to unlock with a password

Fix password error

---

app/sql.js
js/background.js
js/models/conversations.js
js/models/messages.js
js/modules/data.js
js/modules/loki_message_api.js
js/modules/loki_public_chat_api.js
libtextsecure/errors.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
libtextsecure/sendmessage.js
preload.js

*Seems* to be on parity with what we had before, likely silly bugs throughout

Squash and clean of old PRs, move towards sending cleartext again

---

stylesheets/_modules.scss
ts/components/conversation/Message.tsx

Public badge

---

.eslintrc.js
.gitignore
js/models/conversations.js
js/models/messages.js
js/modules/loki_message_api.js
js/modules/web_api.js
js/views/conversation_search_view.js
libloki/test/metrics.js
libloki/test/storage_test.js
libtextsecure/helpers.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
libtextsecure/test/_test.js
libtextsecure/test/fake_web_api.js
libtextsecure/test/in_memory_signal_protocol_store.js
test/metadata/SecretSessionCipher_test.js

Add eslint rule to enforce curlys, run eslint --fix to automatically apply this rule and add swapfiles to gitignore
Only .eslintrc.js and .gitignore have been manually changed

Enforce curlys

---

js/models/conversations.js

When typing a friend request the app was trying to send typing messages

Also don't send typing messages for people we aren't friends with

---

app/config.js
config/default.json
config/production.json
js/modules/loki_message_api.js
js/modules/loki_rpc.js
js/modules/loki_snode_api.js
package.json
preload.js

Use different seed nodes for development vs production and strip 2 characters from pubkey on testnet

Separate testnet

---

js/modules/loki_public_chat_api.js

I removed the reverse function a while ago because I thought the order was backwards then
Not sure if it has changed since or if I was just confused back then

Fix message order

---

libtextsecure/account_manager.js

Add a high-level function `sendPairingRequest` that takes the public key of the primary device.
This function will be used by the secondary device at the registration step.
This uses existing building blocks, since it's very similar to `authoriseSecondaryDevice`, except that the type is different (REQUEST instead of GRANT) and that the primary device pubkey is signed instead of the secondary.
Also, this PR changes `authoriseSecondaryDevice` to attach _BOTH_ signatures (request + grant) to the authorisation sent back to the secondary device and saves that object locally.

[multi-device] Add high-level function to send a pairing request

---

js/modules/link_previews.js
test/modules/link_previews_test.js

Had to change the regex slightly for tenor.com and enforce using https over http.
Fixes #406

Enable link preview for i.imgur.com, tenor and giphy

---

js/models/messages.js

In the message details page:
- show primary device first
- add `(Secondary Device)` in the profileName where necessary

[multi-device] Format message details to show secondary pubkey properly

---

js/background.js
js/modules/loki_public_chat_api.js
libloki/crypto.js

The meat and 2 veg of this series of PRs, covers the actual retrieval and saving of the public token from the server and provides functions to retrieve the token

[Public Authentication] Add token retrieval functions to public chat api

---

js/modules/loki_rss_api.js
ts/components/conversation/Linkify.tsx

Single element results are being parsed as an object and we are expecting an array

Fix feed reader for single element results

---

js/background.js
js/conversation_controller.js
js/models/conversations.js
js/models/messages.js

We were already iterating over all the conversations here so it makes more sense imo
Also renamed function to better reflect the way it was used

Move initialisation of public and rss conversations to fix early load

---

js/background.js
js/conversation_controller.js

Make sure we only initialise special conversations after both registration and storage load have complete

Fix loading during registration

---

libloki/api.js
libtextsecure/message_receiver.js

requires #453 which I will merge into my multi-device branch shortly.

[multi-device] Share primary device profile name upon secondary registration

---

_locales/en/messages.json
background.html
js/background.js
js/views/app_view.js
js/views/qr_dialog_view.js
package.json
preload.js
stylesheets/_conversation.scss
stylesheets/_global.scss
test/index.html
ts/components/MainHeader.tsx
yarn.lock

Adds the ability to view the QR code on desktop.
Resolves #411

Pubkey QR code

---

background.html
test/index.html
ts/components/conversation/MessageDetail.tsx

This option was only hidden from right click
Also remove missing profile.js references since Mik removed it

Remove delete option from more info

---

js/modules/loki_public_chat_api.js
ts/components/conversation/MessageDetail.tsx

Wrap polling function in try finally for safety, fix issue with empty array check and lint

Hotfix for polling loop

---

js/background.js
js/modules/loki_public_chat_api.js
js/modules/loki_rss_api.js

- Addresses #470 (using the user object server object to pull pubkey and nickname instead of individual message annotation)
- Also set up pulling channel meta data (name, avatar) from server (channel annotation) on a regular basis
- other minor refactors

Use user obj / pull channel name/avatar from server

---

js/views/conversation_view.js

Clean up redundant repetition of successive code duplication one after the other

---

js/models/conversations.js

Also clean up a little bit and remove unnecessary async

Stop polling on public chat deletion

---

js/models/conversations.js
js/modules/loki_public_chat_api.js

Stop polling when leaving public chat, only grab the most recent 100 messages on first poll

 Full history and leave chat

---

.eslintrc.js
app/profile_images.js
js/blocked_number_controller.js
js/models/conversations.js
js/models/messages.js
js/modules/data.js
js/modules/loki_p2p_api.js
js/modules/loki_public_chat_api.js
js/modules/loki_rss_api.js
js/modules/loki_snode_api.js
js/views/blocked_number_view.js
js/views/conversation_view.js
libloki/api.js
libloki/modules/local_loki_server.js
libloki/proof-of-work.js
libtextsecure/helpers.js
libtextsecure/key_worker.js
libtextsecure/message_receiver.js
libtextsecure/storage.js
libtextsecure/storage/user.js
libtextsecure/test/in_memory_signal_protocol_store.js
preload.js

I, for one, welcome our new curly overlords

Enforce curlies completely and lint with new settings

---

background.html
js/views/device_pairing_dialog_view.js
js/views/standalone_registration_view.js
libloki/api.js
stylesheets/_global.scss

Show the 3 last words derived from the pubkey instead of the pubkey to help the user compare devices.

[multi-device] Show 3 last mnemonic representation of public key

---

js/modules/loki_message_api.js
js/modules/loki_public_chat_api.js

- sends (id, author) pair for the message quoted
- extracts them from annotations upon receiving
- closes #472

Enable quotes in public chats

---

app/profile_images.js
js/models/conversations.js
package.json
ts/components/Avatar.tsx
ts/components/JazzIcon/JazzIcon.tsx
ts/components/JazzIcon/Paper.tsx
ts/components/JazzIcon/RNG.tsx
ts/components/JazzIcon/index.tsx
yarn.lock

These are the new JazzIcons, i've also ported it to iOS though they have a very minor issue of slightly different hue colours (which aren't noticeable unless you look super carefully)
I've kept the logic of `profileImages` as is since we may use it in the future

Profile icons

---

libtextsecure/message_receiver.js

This PR will make the secondary device send friend requests (empty message) to all the contact received from the primary device, automatically upon receiving the contact list.
The logic to extract the contact infos from the sync message is similar to `handleContacts`.
On the receiving end, the logic to automatically accept a friend request sent by a secondary device is already in.

[multi-device] Auto friend request to sync contacts

---

app/sql.js
js/background.js
js/modules/data.js
libloki/storage.js

Kudos to Mikunj for pointing this out.

[multi-device] Remove rejected authorisation from database

---

js/modules/loki_public_chat_api.js
js/views/conversation_view.js
preload.js
stylesheets/_mentions.scss
stylesheets/_modules.scss
stylesheets/_variables.scss
ts/components/conversation/AddMentions.tsx
ts/components/conversation/Emojify.tsx
ts/components/conversation/Message.tsx
ts/components/conversation/MessageBody.tsx
ts/components/conversation/Quote.tsx
ts/types/Util.ts
tslint.json

- More robust parsing of input (can mention multiple members; takes into account the cursor position).
- Replaces @[pubkey] in messages with profile names with custom formatting.

Custom message rendering of mentions

---

libtextsecure/message_receiver.js

Upon receiving a friend request, fetch device mapping from server to know if the primary device is already a friend

[multi-device] Fetch device mapping from server

---

js/views/standalone_registration_view.js
libloki/crypto.js
libtextsecure/account_manager.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js

[multi-device] Use file server device mapping

---

js/modules/loki_app_dot_net_api.js

Update the signing logic for public chat to use the new signing style with strictly defined payload

Signing update

---

_locales/en/messages.json
background.html
js/views/nickname_dialog_view.js
js/views/standalone_registration_view.js

Also block displayname characters in the edit display name menu and change spaces to underscores

Display name restrictions 2

---

background.html
js/modules/loki_app_dot_net_api.js
js/modules/loki_file_server_api.js
js/modules/loki_message_api.js
js/modules/web_api.js
js/views/conversation_view.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js

Refactor the attachment uploading code to work with public chats
Public chats do not encrypt/decrypt their attachments
Disable file attachments for friend requests

Group attachments

---

package.json
yarn.lock

Upgraded so it can work with mac signing.

Upgraded electron-builder

---

_locales/en/messages.json
package.json

Update change nickname message

---

background.html

Final change

---

app/sql.js
libloki/api.js
libloki/storage.js

First little chunk of my multi device work
No added features, just some bugs that I tidied up along the way

Unique constraint and prevent some undefined bugs

---

_locales/en/messages.json
js/models/conversations.js
js/views/conversation_view.js
js/views/inbox_view.js
libloki/storage.js
libtextsecure/message_receiver.js
ts/components/ConversationListItem.tsx
ts/components/LeftPane.tsx

Add explicit isSecondary flag to conversation list items so they can remain hidden in the menu after they become friends etc

isSecondary flag

---

libloki/api.js

Remove (hopefully) last place the type of a pairing request is being checked

Fix pairing error

---

js/views/conversation_view.js
stylesheets/_conversation.scss
ts/components/conversation/Message.tsx

- deactivate message buttons for RSS (reply etc)
- hide input bar in RSS, replace it with some padding
- fixes #476

Clean up RSS conversation

---

js/models/conversations.js
js/models/messages.js
libtextsecure/outgoing_message.js

Trigger friend request received update for the correct device conversation, throttle the sending of automated friend requests and don't send them to devices which sent *us* a friend request

Throttle automated friend requests + bugfix

---

js/background.js
js/models/conversations.js
js/models/messages.js
libloki/api.js
libloki/storage.js
libtextsecure/account_manager.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
libtextsecure/sendmessage.js
preload.js

Enable sync messages
Fix the "note to self" conversation for secondary devices
Make sure sync messages are sent properly

[multi-device] Sync messages

---

_locales/en/messages.json
background.html
js/views/device_pairing_dialog_view.js
preload.js

Add link to unpair device:
User needs to confirm in a new view:

[multi-device] Allow unpairing device

---

libloki/api.js

`conversation.safeGetVerified()` returns a promise so we needed to wait for it.
The bug is subtle since we perform a enum conversion, and use a default case that gobs every unexpected values.
NOTE: the diff is easier to read with "hide whitespace changes" ON

[multi-device] Fix contact status in createContactSyncProtoMessage

---

.eslintrc.js
_locales/en/messages.json
background.html
js/models/conversations.js
js/models/messages.js
js/modules/loki_app_dot_net_api.js
js/modules/signal.js
js/views/bulk_edit_view.js
js/views/conversation_view.js
stylesheets/_conversation.scss
stylesheets/_modules.scss
test/index.html
ts/components/conversation/BulkEdit.tsx
ts/components/conversation/Image.tsx
ts/components/conversation/Message.tsx
tslint.json

- select multiple messages by left-clicking on them
- when at least one message is selected it enters a *multi-select* mode with an additional menu to delete selected messages or cancel the selection.

Select multiple messages and bulk deletion

---

js/background.js
js/models/conversations.js
libloki/api.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js

Send contact sync message when becoming friends with contact and auto accept/send friend requests when receiving contact sync

[multi-device]Contact syncing

---

js/background.js
js/models/conversations.js
js/models/messages.js
libtextsecure/message_receiver.js

Trigger the end session code if you receive a friend request from a friend, which allows dropped sessions to more easily be reestablished

Session reset on fr

---

js/modules/data.js
ts/state/createStore.ts

Dial the logging down a notch

---

ts/components/MainHeader.tsx

mainheader: call setstate only when needed for clipboard

---

js/views/conversation_view.js
main.js
preload.js

I think there is still an issue if you don't have a mic plugged in, not sure how to detect that atm

Disable microphone button when you have disabled permissions

---

package.json
yarn.lock

This should fix issues with building binaries on mac

Upgrade electron-notarize

---

js/background.js
js/models/conversations.js
js/models/messages.js
js/views/app_view.js
js/views/device_pairing_dialog_view.js
libloki/api.js
libloki/storage.js
libtextsecure/account_manager.js
libtextsecure/contacts_parser.js
libtextsecure/message_receiver.js
libtextsecure/test/contacts_parser_test.js

First batch of fixes for bugs found when testing MD
Brief descriptions in commit messages
Also put a simple timestamp guard around the device pairing checks

[multi-device] Bugfixes and throttle pairing check

---

_locales/en/messages.json

[multi-device]Change auto accept message

---

js/modules/loki_app_dot_net_api.js

Prevent "falsy" messageData (which have failed the validation somehow) to trigger the error message `TypeError: Cannot read property 'group' of undefined`. These can simply be filtered out.
Note: Hide whitespace changes for more clarity

Fix errors showing up from invalid public chats

---

ts/components/conversation/TypingBubble.tsx

One more layout tweak needed after the multi select PR.

Add missing margin to typing indicator bubbles

---

js/models/messages.js
ts/components/conversation/Message.tsx

Don't select messages when context menu is shown

---

_locales/en/messages.json
background.html
js/background.js
js/models/conversations.js
js/models/messages.js
js/modules/signal.js
js/views/app_view.js
js/views/conversation_view.js
js/views/invite_friends_dialog_view.js
js/views/message_view.js
libtextsecure/sendmessage.js
protos/SignalService.proto
stylesheets/_conversation.scss
stylesheets/_mentions.scss
test/index.html
ts/components/ConversationListItem.tsx
ts/components/conversation/ConversationHeader.tsx
ts/components/conversation/GroupInvitation.tsx
ts/components/conversation/InviteFriendsDialog.tsx

Public chat conversations now have a button to send invitations one or more friends to join the chat. The invitation will appear as a "card" in friends' DM.
Future work: once we can get member lists, show which friends are members.

Public chat invitations

---

js/modules/loki_file_server_api.js

Fix DEVICE_MAPPING_USER_ANNOTATION_TYPE

---

stylesheets/_conversation.scss

Just a small tweak to make text readable in dark mode.

Tweak style for group invitations in dark mode

---

_locales/en/messages.json
js/background.js
js/modules/loki_app_dot_net_api.js
js/views/conversation_view.js
preload.js

This fixes the error / bug that occurs when a user's clock is out of sync with the server and messages fail to send.
Now, when the user's clock is out of sync, a toast appears on message send which prompts them to update their clock.

System clock

---

js/background.js
stylesheets/_modules.scss
ts/components/Avatar.tsx
ts/components/JazzIcon/Paper.tsx
ts/components/MainHeader.tsx
ts/components/UserDetailsDialog.tsx

Relates to #655 
Close  showUserDetailsDialog when click outside of it.
Enlarge the avatar when clicked and in the ShowUserDetailsDialog

655 clickable profile

---

js/modules/loki_app_dot_net_api.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js

These changes fix multi-device profile sharing.
Profile pictures were not syncing correctly to secondary device and these changes seem to fix it.

Fix minor profile picture bugs.

---

_locales/en/messages.json
background.html
js/background.js
js/modules/loki_app_dot_net_api.js
js/modules/signal.js
js/views/app_view.js
js/views/conversation_view.js
js/views/moderators_add_dialog_view.js
js/views/moderators_remove_dialog_view.js
libtextsecure/sendmessage.js
stylesheets/_mentions.scss
ts/components/conversation/ConversationHeader.tsx
ts/components/conversation/InviteFriendsDialog.tsx
ts/components/conversation/ModeratorsAddDialog.tsx
ts/components/conversation/ModeratorsRemoveDialog.tsx

- add moderator panel
- text box for manual input (one 64 character+ pubkey is allowed)
- select from your friends
- remove moderator panel
- bug fix for replying to a message with an image (broken in beta9)
- bug fix for "no friends" listing on invite friends to groups
- other minor guards

Add/Remove Moderators interface

---

js/models/conversations.js
js/views/conversation_view.js
stylesheets/_mentions.scss
ts/components/conversation/ConversationHeader.tsx
ts/components/conversation/ModeratorsAddDialog.tsx
ts/components/conversation/ModeratorsRemoveDialog.tsx

- take out unneeded dollar signs
- make context menu in rss feeds correct
- remove scrollbars from add moderator

Minor fixes and clean up

---

js/views/conversation_view.js
ts/components/conversation/ConversationHeader.tsx

- should address the problem Kee was having after adding a public server

Defeat caching of context menu

---

config/default.json
config/development-1.json
config/development-2.json
config/development.json

Added `public.loki.foundation`

Update seed nodes

---

js/models/conversations.js
js/modules/loki_app_dot_net_api.js
js/views/conversation_view.js
ts/components/conversation/ConversationHeader.tsx

This updates subscriber count in open groups to use the stats obtained from the server.

Display subscriber count for open groups

---

app/sql.js
js/background.js
js/models/messages.js
libloki/api.js

Sort messages by sent_at

---

js/modules/loki_rss_api.js

Keep users IP safe while providing potentially important info about upgrading

pull RSS through file proxy

---

preload.js

Merge when ready, personally I don't see anything blocking it.

Desktop: enable useSnodeProxy and useSealedSender feature flag

---

_locales/en/messages.json
js/expire.js
js/modules/loki_app_dot_net_api.js
js/modules/loki_file_server_api.js
js/modules/loki_rpc.js
js/modules/loki_rss_api.js
js/views/conversation_view.js
js/views/file_input_view.js
js/views/inbox_view.js
libtextsecure/message_receiver.js
stylesheets/_session_left_pane.scss

- lint (mainly seal sender manual adjustments)
- fixes being able to send messages due to expire not having a callback
- also some rss guards

Clearnet fixes

---

js/modules/loki_app_dot_net_api.js

Also improve serverRequest error message

make sure TLS is forced on open groups

---

ts/components/LeftPane.tsx

fix grunt error

---

_locales/en/messages.json
ts/components/conversation/GroupNotification.tsx
ts/components/session/SessionClosableOverlay.tsx

```
$ tslint --format stylish --project .
/Users/travis/build/loki-project/session-desktop/ts/components/session/SessionClosableOverlay.tsx:64:5
ERROR: 64:5   no-unnecessary-local-variable  Unnecessary local variable: friends
ERROR: 140:9  switch-final-break             Final clause in 'switch' statement should not end with 'break;'.
ERROR: 254:5  no-unnecessary-local-variable  Unnecessary local variable: memberList
```
also fix `grunt test` failing due to a trailing . in translations changing expected output.

try to address travis-osx tslint complaints

---

_locales/en/messages.json
js/background.js
js/conversation_controller.js
js/modules/loki_app_dot_net_api.js
ts/components/session/LeftPaneChannelSection.tsx

I didn't dive much into the code so i'm not sure 100% how this all works since there are multiple code paths. I've just applied the basic patches to get open groups up and running

Fix open group joining.

---

js/views/create_group_dialog_view.js

Fix "Update Group" on fresh open group chats

---

.github/workflows/build-binaries.yml
.github/workflows/release.yml
BUILDING.md
build/notarize.js
package.json
yarn.lock

This is the first part of the PR.
This adds in:
- Binary building for any commit pushes on `master`, `development`, `clearnet` and `github-actions` branches
- Creating a draft release for any commits pushed on `master`
Also resolves #779  and resolves #808.
The second part of the PR will be to replace travis in running all tests on a new pull request, as well as remove any old files.

GitHub actions

---

_locales/en/messages.json
js/conversation_controller.js
js/models/conversations.js
js/views/app_view.js
libtextsecure/sendmessage.js
ts/components/session/LeftPaneMessageSection.tsx
ts/components/session/SessionClosableOverlay.tsx

Fixes a few issues:
- New closed group view showing invalid members.
- Sync messages not sent when updating groups.
- Leaving group only deletes the conversation

Closed group fixes.

---

README.md
js/background.js
js/models/conversations.js
js/models/messages.js
js/modules/loki_app_dot_net_api.js
libloki/storage.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
libtextsecure/sendmessage.js
stylesheets/_modules.scss
ts/components/EditProfileDialog.tsx
ts/components/conversation/GroupNotification.tsx
ts/components/session/SessionClosableOverlay.tsx

The following issues have been fixed:
- Linked device sending automatic friend request when it already has keys to setup a session.
- Fix closed group message syncing.
- Fix creating closed groups from a secondary device.
- Minor fixes to auto friend request accepts.
- Fix incorrect message mapping
- Minor fixes.
Refer to commits for specific fixes.
I've tested the best i could but there may be some edge cases that i might have missed.

Multi device fixes

---

js/modules/loki_app_dot_net_api.js
js/modules/loki_public_chat_api.js
libtextsecure/message_receiver.js

Addresses #510 
and also prevents (a flood of) duplicates after running for a while (after multiple close()/reconnect())

Open group polling fix

---

js/modules/loki_app_dot_net_api.js
libtextsecure/outgoing_message.js

Fix friend request for background messages not triggering friend request logic.
This may potentially solve #824.

Friend request bug fix

---

_locales/en/messages.json
about.html
background.html
stylesheets/_modules.scss
stylesheets/_session.scss
stylesheets/_session_left_pane.scss
ts/components/session/ActionsPanel.tsx
ts/components/session/LeftPaneSectionHeader.tsx
ts/components/session/RegistrationTabs.tsx

secretPrompt Fix

---

README.md
_locales/en/messages.json
stylesheets/_conversation.scss
stylesheets/_modules.scss
stylesheets/_session.scss
stylesheets/_session_left_pane.scss
stylesheets/_session_signin.scss
ts/components/EditProfileDialog.tsx
ts/components/conversation/ConversationHeader.tsx
ts/components/conversation/MessageBody.tsx

- Aligned delete message button
- Center textarea session ID text
- Remove search & avatar from conversationHeader for RSS.
- Fix text selection to include only desired elements: ``user-select: none`` for non-selectables.
- Updates all references to 'public chats' to 'open groups'.
- Top bars equivalent heights
- LeftPane buttons aligned with message composition box
- Update onboarding privacy policy, ToS links and text

Various improvements

---

main.js

adjust min size of electron window to 880 X 580 to fit for lower screen resolution
see original issue post in here: 
https://github.com/loki-project/session-desktop/issues/820

Fixissue#820

---

.github/workflows/build-binaries.yml
.github/workflows/release.yml
build/setup-mac-certificate.sh

Only enable signing if we have a certificate on Mac

---

CONTRIBUTING.md
bower.json
debug_log.html
js/modules/debuglogs.js
main.js

Fix documented paths for Windows in CONTRIBUTING.md
Also fixed Support page link which is very broken

loki-messenger => session-desktop

---

ts/components/conversation/ConversationHeader.tsx

Removed the redundant Search Icon in the Message View.
One Test is failing unrelated to the change and I will open an issue for that.

Remove search icon in message view

---

_locales/en/messages.json

For auto-download prep, want to do this separately to make sure changing all these at once is ok.

convert more Signal references to Session

---

js/modules/loki_message_api.js
js/modules/loki_rpc.js
js/modules/loki_snode_api.js
libtextsecure/message_receiver.js
ts/components/SearchResults.tsx
ts/components/conversation/CreateGroupDialog.tsx
ts/components/session/LeftPaneMessageSection.tsx
ts/state/ducks/search.ts

Include friend is search results from the message searchbox
Fixes https://github.com/loki-project/session-desktop/issues/928

Include friend search result #928

---

app/global_errors.js
app/sql.js
package.json
yarn.lock

This should fix #875. 
These changes were taken directly from signal upstream.

Upgrade sql cipher to 4.2.0

---

js/views/conversation_view.js

When the conversation has A LOT of messages and is taking some time to load.

Fix message still loading exception

---

.github/workflows/build-binaries.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

This might fix some of the failing tests related to checking out a repo.

Update checkout action to v2

---

js/background.js

Made some function calls async so they don't block the envelope queue.

Speed up message decryption.

---

js/views/conversation_view.js

Closes #631 
@Bilb solved the issue, please give him all the glory.

Implement Blib's change

---

ts/components/session/SessionSearchInput.tsx

Replace native Context Menu with a syleguided one in SearchInput

---

js/background.js
js/modules/loki_file_server_api.js
libloki/storage.js

This seemed to be a bug introduced with a previous bug fix in which message decryption was sped up.
Old PR: #976 
Also fixed up bugs which occurred when an invalid authorisation was passed.

Fix messages not being created properly in open groups

---

main.js

Fix build failures for release

Hardcode AppId

---

js/modules/loki_app_dot_net_api.js

oversight in #988 affecting failed token retrying

Fix serverRequest retry

---

_locales/en/messages.json
password_preload.js
preload.js
ts/components/session/SessionPasswordModal.tsx
ts/components/session/SessionPasswordPrompt.tsx

Password paste control on MAX_PASSWORD_LEN

---

_locales/en/messages.json
package.json
stylesheets/_session.scss
ts/components/DevicePairingDialog.tsx
yarn.lock

Update refs from ``pair | pairing`` --> ``link | linking``.

Link Device Copy

---

_locales/en/messages.json
stylesheets/_session.scss
stylesheets/_session_left_pane.scss
ts/components/session/ActionsPanel.tsx
ts/components/session/LeftPaneSectionHeader.tsx
ts/components/session/SessionNotificationCount.tsx
ts/components/session/icon/SessionIconButton.tsx

Places 9<sup>+</sup> in notifications bubble for numbers over 9.
Styling of notification bubble generalized and made size-indifferent in positioning.

Notifications icon numeration

---

js/models/conversations.js

fix bug with accept/reject buttons on friend request 

---

js/background.js

Disable sending of send receipt when receiving a friend request message
fixes #989

fix pre approved friend requests

---

ts/components/session/RegistrationTabs.tsx

toast on exception
use a separate mnemonicSeed for signup (generated )and signin (entered by user)

add logs to registration process

---

main.js
preload.js

This fixes the debug and the permission dialogs not showing up.

Fix theme setting not being sent back to main.js

---

js/modules/loki_rpc.js
js/modules/loki_snode_api.js
main.js
package.json
preload.js
yarn.lock

- Added `lokiSnodeAPI.getLnsMapping` that makes an LNS request to a bunch of nodes until it gets at least 3 matching answers, then decrypts the value returning the pubkey.
- Example: `await window.lokiSnodeAPI.getLnsMapping("doyle")` should return `05bf7d78abf034661c691523b009ea...`

API implementation for LNS

---

main.js

password was closed to early and no windows were shown which triggered the app stop

Close the password window once mainwindow is focused

---

js/modules/loki_file_server_api.js

Fix integration tests slipping into release

---

ts/components/session/SessionClosableOverlay.tsx

(React is not happy otherwise)

Add missing key prop to SessionMemberListItem

---

js/modules/loki_message_api.js
js/modules/loki_primitives.js
js/modules/loki_rpc.js
js/modules/loki_snode_api.js
preload.js

- enables onion requests by default
- set onion request hops to 1
- fixes bug in proxy / onion requests not properly handling wrong PoW/timestamp/swarm
- log any sendMessage exceptions

Configurable onion request hops and wrong PoW/timestamp/swarm fixes for proxy/ORs

---

ts/components/ConversationListItem.tsx

Closes #1059 
I enabled mention rendering in the Sidepanel. I don't show the username, but that will be fixed once we use Redux.

Enable Mention Rendering in sidepanel

---

app/sql.js
js/background.js
js/modules/data.js
js/modules/loki_app_dot_net_api.js

This should fix up cpu usage spikes.
Spikes also occur when we use 3 hop onion requests. I'll be working on that in another PR.

Fix unnecessary db calls

---

stylesheets/_session.scss
ts/components/session/SessionNotificationCount.tsx

Fixes alignment issues with new font and notification alignment.

Notification Count Positioning

---

libtextsecure/message_receiver.js

This is a temporary fix for ignoring empty messages.

Stop processing message when it is empty

---

config/default.json
config/development.json
config/local-development.json
config/swarm-testing.json
js/modules/loki_snode_api.js
main.js

update seedNode format to include protocol and remove port as separate option.
Add ip_url as a fallback to fix #1063 while I'm at it
Add all new HTTPS seed nodes in production

Seed https support

---

package.json
ts/components/ConversationListItem.tsx
ts/components/session/LeftPaneContactSection.tsx
ts/state/selectors/conversations.ts

Patch for #1118.
Contacts now filtering properly.

FR Duplication Fixes | Patch for #1118 

---

js/modules/loki_snode_api.js

fix snodes retrieval from seed

---

js/models/conversations.js
js/models/messages.js
libloki/api.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js

This PR makes changes based on: https://github.com/loki-project/session-protocol-docs/issues/4#issuecomment-629951008
I've tested one to one friend request logic and it works, still need to try multi device and closed groups.

Made changes for new protocol backward compatibility

---

test/index.html

tests: move expires after libtextsecure

---

js/modules/loki_app_dot_net_api.js

Quick fix for integration tests

Pubkeys don't matter if proxy/onion are off

---

js/modules/loki_app_dot_net_api.d.ts
js/modules/loki_app_dot_net_api.js
js/modules/loki_message_api.d.ts
js/modules/loki_message_api.js
js/modules/loki_public_chat_api.d.ts
js/modules/loki_public_chat_api.js
libloki/test/crypto_test.js
ts/session/crypto/MessageEncrypter.ts
ts/session/messages/outgoing/OpenGroupMessage.ts
ts/session/messages/outgoing/content/data/group/ClosedGroupChatMessage.ts
ts/session/sending/MessageSender.ts
ts/test/session/messages/ClosedGroupChatMessage_test.ts
ts/test/session/messages/OpenGroupMessage_test.ts
ts/window/index.ts
tsconfig.json

This is just the implementation PR. Test PR will be seperate as to not block others.

Message Sender

---

package.json
ts/session/crypto/MessageEncrypter.ts
ts/session/sending/MessageSender.ts
ts/test/session/sending/MessageSender_test.ts
yarn.lock

I added `p-retry` as it's a fairly small and extendible retry library which we might want to use in other parts of the code in the future.

Message sender retry

---

js/modules/loki_primitives.js

- remove unnecessary rethrows
- remove the need to "configure" log (not sure why that was added, can't reproduce any issues with it removed)

Clean up loki_primitives

---

about_preload.js
debug_log_preload.js
password_preload.js
permissions_popup_preload.js

This basically stopped debug log from working

Fix missing ByteBuffer in preloads.

---

ts/session/sending/MessageQueue.ts
ts/session/types/PubKey.ts

Fixes:
- Same job queue not used when sending messages
- Multiple events firing for the same message send
- PubKey.key case sensitivity

Fix message queue

---

_locales/en/messages.json
js/models/conversations.js
js/models/messages.js
js/modules/loki_app_dot_net_api.d.ts
js/signal_protocol_store.js
libloki/api.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
libtextsecure/sendmessage.js
ts/session/index.ts
ts/session/messages/outgoing/content/SessionEstablishedMessage.ts
ts/session/messages/outgoing/content/sync/ClosedGroupSyncMessage.ts
ts/session/messages/outgoing/content/sync/ContactSyncMessage.ts
ts/session/messages/outgoing/content/sync/OpenGroupSyncMessage.ts
ts/session/messages/outgoing/content/sync/SentSyncMessage.ts
ts/session/messages/outgoing/content/sync/SyncReadMessage.ts
ts/session/messages/outgoing/content/sync/VerifiedSyncMessage.ts
ts/session/messages/outgoing/content/sync/index.ts
ts/session/sending/MessageSender.ts
ts/session/utils/SyncMessageUtils.ts

Move the sync message of closed groups open groups and contacts to the new pipeline

Other messages new sending

---

js/background.js
ts/session/messages/outgoing/content/SessionRequestMessage.ts
ts/session/protocols/SessionProtocol.ts
ts/test/session/protocols/SessionProtocol_test.ts

Implements the expiry part of the protocol.

Add session request expiry checks

---

js/models/conversations.js
js/models/messages.js
ts/session/instance.ts
ts/session/messages/outgoing/content/data/DataMessage.ts
ts/session/messages/outgoing/content/data/DeviceUnlinkMessage.ts
ts/session/messages/outgoing/content/data/ExpirationTimerUpdateMessage.ts
ts/session/messages/outgoing/content/data/GroupInvitationMessage.ts
ts/session/messages/outgoing/content/data/group/ClosedGroupChatMessage.ts
ts/session/messages/outgoing/content/data/group/ClosedGroupMessage.ts
ts/session/messages/outgoing/content/data/mediumgroup/MediumGroupChatMessage.ts
ts/session/messages/outgoing/content/data/mediumgroup/MediumGroupMessage.ts
ts/session/messages/outgoing/content/receipt/ReceiptMessage.ts
ts/session/messages/outgoing/content/sync/SentSyncMessage.ts
ts/session/messages/outgoing/content/sync/SyncReadMessage.ts
ts/session/sending/MessageQueue.ts
ts/session/sending/MessageQueueInterface.ts
ts/session/utils/SyncMessageUtils.ts
ts/test/session/sending/MessageQueue_test.ts

These changes make it so we handle sync messages the way signal handled them (not the best way imo but it works)

Change how sync messages are handled

---

js/views/create_group_dialog_view.js
ts/test/session/utils/SyncMessage_test.ts

Fixed group names modal, also `yarn lint-full` fixed up `SyncMessage_test.ts`

Fix Group Names

---

js/models/conversations.js
libtextsecure/crypto.d.ts
libtextsecure/index.d.ts
stylesheets/_modules.scss
ts/receiver/dataMessage.ts
ts/session/utils/Attachments.ts
ts/window.d.ts

This PR fixes:
- Attachment not being sent and handled properly
- Messages sending incorrect timestamp
- Minor UI fixes

Fix attachments

---

js/background.js
js/models/conversations.js
js/models/messages.js
js/views/inbox_view.js
ts/components/session/SessionGroupSettings.tsx
ts/receiver/dataMessage.ts
ts/session/messages/outgoing/content/data/group/ClosedGroupUpdateMessage.ts
ts/session/messages/outgoing/content/sync/SentSyncMessage.ts
ts/session/utils/Protobuf.ts
ts/session/utils/index.ts
ts/test/session/utils/Promise_test.ts

This PR Fixes:
- Group update not being sent to kicked member
- Group message syncing if you're the only one in the group
- Incorrect protobuf encoding of group id in `SentSyncMessage`.

Closed group fixes

---

ts/receiver/contentMessage.ts
ts/receiver/dataMessage.ts
ts/receiver/multidevice.ts
ts/receiver/receiver.ts

handle empty buffer as null fields when needed

ignore other empty buffers which should be null after protobuf decode

---

ts/receiver/receiver.ts
ts/session/snode_api/serviceNodeAPI.ts
ts/session/snode_api/swarmPolling.ts

It is an error to try to use the PubKey object in the json request to a snode...

Fix retrieving with pubkey object

---

js/models/conversations.js
js/models/messages.js
js/views/invite_contacts_dialog_view.js
libtextsecure/contacts_parser.js
ts/components/DevicePairingDialog.tsx
ts/components/conversation/InviteContactsDialog.tsx
ts/components/session/LeftPaneMessageSection.tsx
ts/components/session/SessionClosableOverlay.tsx
ts/receiver/dataMessage.ts
ts/receiver/multidevice.ts
ts/session/protocols/MultiDeviceProtocol.ts
ts/session/types/OpenGroup.ts
ts/session/utils/SyncMessage.ts
ts/state/selectors/conversations.ts
ts/test/test-utils/utils/message.ts

* handle message sending events for open groups

Fix open groups ui

---

js/models/conversations.js
js/models/messages.js

* handle sync for closed groups update as we do for regular messages

handle sync for closed groups update as we do for regular messages

---

js/models/conversations.js
libtextsecure/account_manager.js
ts/components/DevicePairingDialog.tsx
ts/components/EditProfileDialog.tsx
ts/components/session/ActionsPanel.tsx
ts/session/messages/outgoing/content/link/DeviceLinkGrantMessage.ts
ts/session/messages/outgoing/content/link/DeviceLinkRequestMessage.ts

when our primary device updates the avatar, we wait for a sync message
to know about this update.
Once this message comes in, it updates the avatar on the conversation,
but nothing refresh the ActionPanel component.
This commit makes sure we listen for changes on our conversation to
trigger this refresh.

update our top left avatar on avatar changes

---

ts/session/types/PubKey.ts
ts/test/session/crypto/MessageEncrypter_test.ts

needs more testing but so far it looks good

add the group id from mobile as valid pubkey key

---

js/models/blockedNumbers.js
js/models/conversations.js
js/views/conversation_view.js
libtextsecure/account_manager.js
libtextsecure/sendmessage.js
ts/components/ConversationListItem.tsx
ts/components/conversation/ConversationHeader.tsx
ts/components/session/SessionGroupSettings.tsx
ts/receiver/groups.ts
ts/receiver/multidevice.ts
ts/state/ducks/conversations.ts
ts/state/selectors/conversations.ts
ts/test/state/selectors/conversations_test.ts
ts/util/blockedNumberController.ts

* make UI show when a user/group is toggled between blocked/unblocked
* trigger a contact sync or closed group with the `blocked` field set, so our other devices gets the new blocked status when we toggle a blocked user.
* update UI when user blocks a group (hide option to disappear message from menu and right panel)

Sync blocked numbers

---

background.html
background_test.html
js/conversation_controller.js
js/models/conversations.js
test/index.html
ts/receiver/dataMessage.ts

* enable back read receipt sending message
* enable back delivery receipt message
* cleanup unused stuff

Fix read receipt

---

package.json

Fix build-release command

---

js/models/conversations.js
stylesheets/_emoji.scss
stylesheets/_session_conversation.scss
ts/components/conversation/Emojify.tsx
ts/components/conversation/Message.tsx
ts/components/conversation/MessageBody.tsx
ts/components/session/SessionProgress.tsx
ts/components/session/conversation/SessionCompositionBox.tsx
ts/components/session/conversation/SessionConversation.tsx
ts/components/session/conversation/SessionConversationManager.tsx
ts/components/session/conversation/SessionRecording.tsx
ts/state/reducer.ts
ts/state/selectors/conversations.ts

Reverts loki-project/session-desktop#1281

Revert "Build and Lint Fixes"

---

ts/receiver/receiver.ts

when pulling public message, use the MultiDeviceProtocol to check if this message is coming from us rather than checking the cached values

when pulling public message, use the MultiDeviceProtocol to check

---

_locales/en/messages.json
app/sql.js
js/background.js
js/modules/loki_file_server_api.js
preload.js
ts/components/session/ActionsPanel.tsx
ts/components/session/LeftPaneSettingSection.tsx
ts/components/session/RegistrationTabs.tsx
ts/components/session/settings/SessionSettings.tsx
ts/components/session/settings/SessionSettingsHeader.tsx
ts/receiver/multidevice.ts
ts/session/protocols/MultiDeviceProtocol.ts
ts/test/session/protocols/MultiDeviceProtocol_test.ts
ts/window.d.ts

This PR does the following:
- Wipes secondary devices
- Removes all pairing authorisation from database
- Disables fetching from file server
- Disables handling of pairing messages

Disable multi device

---

_locales/en/messages.json
stylesheets/_conversation.scss
stylesheets/_modal.scss
stylesheets/_session.scss
stylesheets/_session_left_pane.scss
stylesheets/_session_signin.scss
stylesheets/themes.scss
ts/components/session/LeftPaneMessageSection.tsx
ts/components/session/settings/SessionSettings.tsx
ts/session/types/OpenGroup.ts

minor fixes for light mode
Needs https://github.com/loki-project/session-desktop/pull/1322 to be merged first

Fix light mode

---

ts/receiver/receiver.ts
ts/session/snode_api/serviceNodeAPI.ts
ts/session/snode_api/swarmPolling.ts

Not sure this completely resolve #995 yet, but it should help

fix polling logic on network errors #995

---

js/models/messages.js
js/views/conversation_view.js
stylesheets/_modules.scss

Before: 
first issue is "Secondary Device" shown but they are not
second issue is the sent badge on the right with an incorrect size
After:

Message detail view fixes

---

stylesheets/_modules.scss
stylesheets/_session_group_panel.scss

fix the media panel with lots of media (bottom button hidden)

---

_locales/id/messages.json
_locales/ja/messages.json
_locales/pl/messages.json
_locales/vi/messages.json
tools/mapAndroidTranslationsToDesktop.py

Add the Polish, Japanese, Vietnamese and Indonesian translations from mobile

Add translations

---

app/sql.js
js/models/messages.js
preload.js
ts/receiver/dataMessage.ts

* drop the textsecure prefix from incoming message
* so this works with existing groups, we have to drop it from group conversations in the db, so add a migration to drop this prefix

Fix ssk groups

---

app/sql.js
background.html
js/views/conversation_view.js

we drop the convo with the less messages to keep the unique constraint on
conversation IDs

Handle duplicate convo prefix remove

---

js/modules/loki_app_dot_net_api.js
js/modules/loki_push_notification_server_api.js

* Stop retries server request stop after 4 failing attempts 
* update apns url

Stop retries server request stop after 4 failing attempts and update apns url

---

ts/session/snode_api/serviceNodeAPI.ts

this can happen on node restart for instance

mark node as bad if it returns difficulty 100

---

_locales/de/messages.json
_locales/en/messages.json
_locales/es/messages.json
_locales/fr/messages.json
_locales/id/messages.json
_locales/it/messages.json
_locales/ja/messages.json
_locales/pl/messages.json
_locales/pt_BR/messages.json
_locales/ru/messages.json
_locales/vi/messages.json
js/views/invite_contacts_dialog_view.js
preload.js
stylesheets/_session.scss
ts/components/MainViewController.tsx
ts/components/conversation/CreateGroupDialog.tsx
ts/components/session/SessionClosableOverlay.tsx
ts/session/messages/outgoing/content/data/ExpirationTimerUpdateMessage.ts

* group size is now max 20
* add the prefix to groupId in a expiration timer update message too
* enable SSK

Enable sender keys groups

---

js/background.js
libtextsecure/account_manager.js
libtextsecure/test/account_manager_test.js
main.js
preload.js
test/crypto_test.js
ts/components/session/RegistrationTabs.tsx
ts/window.d.ts

move to new identity key mechanism
now we do as followed:
• Generate 16 bytes of random data
• Add 16 bytes of zeros
• Use the 16 bytes of random + 16 bytes of zeros to generate an ED25519 key pair
• Convert the ED25519 key pair to an X25519 key pair
All of this is happening with libsodiumm called over IPC

Switch key mechanism

---

js/background.js
libtextsecure/account_manager.js
libtextsecure/test/account_manager_test.js
main.js
package.json
preload.js
test/crypto_test.js
ts/components/session/RegistrationTabs.tsx
ts/window.d.ts

Now we do as followed:
• Generate 16 bytes of random data
• Add 16 bytes of zeros
• Use the 16 bytes of random + 16 bytes of zeros to generate an ED25519 key pair
• Convert the ED25519 key pair to an X25519 key pair
All of this is happening with libsodiumm called over IPC

Improved key pair generation mechanism

---

js/models/conversations.js
js/modules/loki_app_dot_net_api.d.ts
js/modules/loki_app_dot_net_api.js
js/modules/loki_file_server_api.d.ts
js/modules/loki_public_chat_api.js
preload.js
ts/receiver/attachments.ts
ts/session/snode_api/onions.ts
ts/window.d.ts

Use `useFileOnionRequestsV2` feature flag to enable

Optionally use v3/lsrpc endpoint for more compact (base64) file downloads

---

.github/workflows/pull-request.yml
ts/session/snode_api/onions.ts

Do not use the v3 onion request protocol for PN calls to our PN server

do not use v3 for live.apns.getsession.org PN calls

---

stylesheets/_session_left_pane.scss

Fix font for conversation list item title

---

_locales/en/messages.json
_locales/fr/messages.json
_locales/ru/messages.json
password_preload.js
preload.js
ts/components/Lightbox.tsx
ts/components/session/RegistrationTabs.tsx
ts/components/session/SessionPasswordModal.tsx
ts/components/session/SessionPasswordPrompt.tsx
ts/components/session/SessionSeedModal.tsx
ts/components/session/settings/SessionSettings.tsx
ts/test/session/unit/utils/Password.ts
ts/util/passwordUtils.ts
ts/window.d.ts

Relates #1446
Also, make sure all warning messages have 64 as limit and not 50

Fix the password length limit when not setting a new password

---

package.json

This reverts commit 258a7b83e88a5de10c3167c2939877d8ecef5f18.

Revert "bump to v1.4.9"

---

preload.js
ts/receiver/closedGroups.ts
ts/receiver/contentMessage.ts
ts/session/group/index.ts
ts/window.d.ts

and remove request encryption keypair handling

send the keypair to added members if we are admin

---

CONTRIBUTING.md
README.md
about.html
main.js

- update links on about page
- replace gross pixelated logo on about page
- update menu links for release notes, bug reports, and support
- update names and links in README and CONTRIBUTING

Replace loki -> oxen in UI

---

ts/session/snode_api/onions.ts

If storage server returns 502 then mark the path bad

Make storage server error code 502 mark the path as bad

---

_locales/en/messages.json
js/background.js
protos/SignalService.proto
stylesheets/_conversation.scss
ts/components/conversation/GroupInvitation.tsx
ts/interactions/message.ts
ts/models/conversation.ts
ts/models/message.ts
ts/opengroup/opengroupV2/OpenGroupServerPoller.ts
ts/receiver/closedGroups.ts
ts/receiver/dataMessage.ts
ts/receiver/receiver.ts
ts/session/messages/outgoing/visibleMessage/GroupInvitationMessage.ts
ts/session/snode_api/onions.ts
ts/session/utils/syncUtils.ts
ts/test/session/unit/messages/GroupInvitationMessage_test.ts

fallback to using envelope timestamp if the dataMessage.timestamp is not set

Fix message duplication

---

ts/fileserver/FileServerApiV2.ts
ts/receiver/attachments.ts

fix avatar download on restore when linking device

---

js/background.js
ts/components/session/SessionNicknameDialog.tsx
ts/models/conversation.ts
ts/window.d.ts

also add some type for it and remove unused props

fixup nickname dialog for enter key pressed event

---

preload.js
ts/session/crypto/BufferPadding.ts
ts/test/types/Attachment_test.ts
ts/types/Attachment.ts
ts/types/MIME.ts

Fix attachment extension vnd

---

.github/workflows/release.yml

this is causing a forbidden with publishing to github

disable draft release on pr to master

---

_locales/en/messages.json
js/views/session_confirm_view.js
ts/components/session/SessionNicknameDialog.tsx
ts/receiver/closedGroups.ts
ts/session/sending/MessageQueue.ts

* Added non-durable sending method.

WIP: Closed group reliability

---

ts/test/types/Attachment_test.ts
ts/types/Attachment.ts

use attachment name when we have one for file saving

---

package.json
ts/components/session/ActionsPanel.tsx

remove dialog unstable attachment

---

ts/models/message.ts
ts/types/Attachment.ts

do not overwrite attachment name on sending side

---

_locales/en/messages.json
ts/components/conversation/ConversationHeader.tsx
ts/components/conversation/Message.tsx
ts/components/session/conversation/SessionConversation.tsx
ts/components/session/menu/ConversationHeaderMenu.tsx
ts/components/session/menu/Menu.tsx
ts/models/conversation.ts
ts/test/test-utils/utils/message.ts

add a HeaderOption to change the notification settings for each convo

---

.github/workflows/build-binaries.yml
.github/workflows/release.yml

run test on pr to clearnet
run build binaries on push to clearnet
run draft release on push to master

rewrite actions

---

ts/data/data.ts
ts/receiver/attachments.ts
ts/session/onions/onionPath.ts
ts/session/onions/onionSend.ts
ts/session/snode_api/SNodeAPI.ts
ts/session/snode_api/lokiRpc.ts
ts/session/snode_api/onions.ts
ts/session/snode_api/snodePool.ts
ts/session/snode_api/swarmPolling.ts
ts/session/utils/Promise.ts
ts/test/session/unit/onion/OnionErrors_test.ts

if not enough snodes or no snodes at all, a request to the seed node is
made instead

store snodes list on db, use them if possible on app start

---

_locales/en/messages.json
ts/components/OnionStatusDialog.tsx
ts/components/conversation/Message.tsx
ts/components/session/icon/SessionIcon.tsx

This PR contains multiple items.
- Onion path UI
- Modals refactored to use React and Redux.
- Audio messages playback speed toggle between 2x and 1x speed.
- Confirmation dialog upon pasting a URL when composing a message warning of metadata usage which alters Session settings.

Merge dialogs

---

_locales/en/messages.json
ts/components/conversation/Linkify.tsx
ts/components/conversation/Message.tsx

Shows a popup confirmation modal before visiting a link in a message.

Link visit confirmation

---

ts/session/snode_api/snodePool.ts

Fix snode return

---

ts/components/OnionStatusPathDialog.tsx
ts/components/session/ActionsPanel.tsx
ts/components/session/ModalContainer.tsx

fix spinner for onion path loading dialog

---

ts/components/ConversationListItem.tsx
ts/components/conversation/ConversationHeader.tsx
ts/components/session/conversation/SessionConversation.tsx
ts/components/session/menu/ConversationHeaderMenu.tsx
ts/components/session/menu/ConversationListItemContextMenu.tsx
ts/components/session/menu/Menu.tsx
ts/models/conversation.ts
ts/state/ducks/conversations.ts
ts/test/session/unit/selectors/conversations_test.ts

Notifications added to conversations context menu
Pin conversations added to header menu

Header and conversation menus updates

---

ts/components/conversation/InviteContactsDialog.tsx
ts/components/conversation/ModeratorsAddDialog.tsx
ts/components/conversation/ModeratorsRemoveDialog.tsx
ts/components/session/SessionConfirm.tsx
ts/components/session/SessionWrapperModal.tsx

Added a listener to close modals when the area outside of the visible modal is clicked.
Some deletions of unused imports/code.

Close modals easier

---

_locales/en/messages.json
ts/components/conversation/InviteContactsDialog.tsx
ts/components/conversation/ModeratorsAddDialog.tsx
ts/components/conversation/ModeratorsRemoveDialog.tsx
ts/components/session/SessionConfirm.tsx
ts/components/session/SessionSeedModal.tsx
ts/components/session/SessionWrapperModal.tsx
ts/components/session/conversation/SessionConversation.tsx

Displays a confirmation modal if the user is about to send their recovery phrase in a message.

Send seed confirmation

---

ts/components/session/conversation/SessionCompositionBox.tsx
ts/session/messages/outgoing/visibleMessage/VisibleMessage.ts
ts/session/utils/Attachments.ts
ts/session/utils/AttachmentsV2.ts
ts/test/session/unit/messages/ChatMessage_test.ts

Fixes https://github.com/oxen-io/session-android/issues/669

Fix link preview embeded url

---

app/sql.js

fix login with password

---

ts/receiver/closedGroups.ts

Some group updates were not received between linked devices.

Fix group key pair cache issue

---

ts/components/session/conversation/SessionCompositionBox.tsx

fix send link preview keep being shown

---

package.json
ts/components/session/conversation/SessionCompositionBox.tsx
ts/interactions/conversationInteractions.ts
yarn.lock

fix replying to message focus composition box

---

stylesheets/_session.scss

Relates #1758 and #1898 and #1901

Keep line breaks when message has some new lines

---

ts/components/session/conversation/SessionCompositionBox.tsx

disable sending on enter while composing

---

_locales/en/messages.json
ts/components/session/settings/SessionSettings.tsx

Adds a button that links to the Session survey.

Adding survey button to settings menu.

---

app/logging.js

Fix crash on rotating the file log

---

ts/session/utils/syncUtils.ts

otherwise the whole app freezes on a big database

make sure to use cached convos for sync logic

---

js/modules/settings.js
ts/components/settings/section/CategoryPrivacy.tsx
ts/data/settings-key.ts
ts/models/conversation.ts
ts/models/message.ts
ts/receiver/contentMessage.ts
ts/util/accountManager.ts

also turn off typing message by default

use variables for common settings key

---

ts/components/conversation/SessionMessagesList.tsx

do not call home/end events if target is textbox

---

_locales/en/messages.json
main.js

send message to him => send message to them

fix typo call missed toast 

---

package.json
preload.js

1.8.2 with calls

---

.github/workflows/build-binaries.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
ts/models/conversation.ts
ts/receiver/closedGroups.ts
ts/receiver/contentMessage.ts
ts/session/group/closed-group.ts
ts/session/utils/calling/CallManager.ts
ts/state/selectors/conversations.ts

also, do not filter closed group based on the isApproved field in redux

create closed group mark as approved

---

ts/receiver/closedGroups.ts

use source instead of senderIdentity to check for approved new group

---

preload.js
ts/components/avatar/AvatarPlaceHolder/AvatarPlaceHolder.tsx
ts/session/utils/calling/CallManager.ts
ts/state/ducks/call.tsx
ts/test/session/unit/utils/Emoji_test.ts
ts/test/session/unit/utils/Initials_test.ts
ts/test/session/unit/utils/TimerBucket_test.ts
ts/util/emoji.ts
ts/util/getInitials.ts

the caller is just supposed to accept the offer and send an answer back

trigger a new offer on connect fail if we are caller

---

README.md

fixing the damn readme !!!

---

ts/components/dialog/UpdateGroupMembersDialog.tsx

Fix opening of group member list from crashing app.

fix group members sorting causing error.

---

_locales/en/messages.json

Clarify that the search box can now also find individual messages

---

_locales/en/messages.json
stylesheets/_session_conversation.scss
ts/interactions/conversations/unsendingInteractions.ts

originally from #2263 by @ianmacd

When deleting multiple messages, inform the user of the number

---

ts/components/conversation/ConversationHeader.tsx

Fix typo in constant name.

---

stylesheets/_session_left_pane.scss
ts/mains/password_start.tsx

fix: revert unread count color

---

package.json

Hopefully this fixes build issues with the sass and sass:watch commands

Fixed Parcel SASS build flags

---

package.json
ts/components/dialog/ReactListModal.tsx

also double click on the picker does not reply to original message

Merge clearing own reaction from modal closes it

---

ts/node/sql.ts

Also, shorten from the start and not from the middle!

fix: shorten further the last message

---

ts/components/conversation/SessionLastSeenIndicator.tsx
ts/components/conversation/SessionMessagesList.tsx
ts/state/ducks/conversations.ts
ts/state/selectors/conversations.ts

fix: do not scroll back to unread banner when deleting msgs

---

stylesheets/_session.scss
stylesheets/_session_theme.scss
stylesheets/_variables.scss
ts/components/conversation/message/message-content/MessageContent.tsx
ts/components/conversation/message/message-content/MessageContentWithStatus.tsx
ts/components/conversation/message/message-item/GenericReadableMessage.tsx

looks like node-sass tries to be too clever

fix: rounded corners around messages

---

ts/components/conversation/Image.tsx
ts/components/conversation/SessionQuotedMessageComposition.tsx
ts/components/conversation/message/message-content/MessageContent.tsx
ts/state/selectors/conversations.ts

fix: disable having some corner large and small for message bubbles

---

ts/components/conversation/message/message-content/MessageReactions.tsx
ts/components/conversation/message/reactions/Reaction.tsx
ts/components/conversation/message/reactions/ReactionPopup.tsx
ts/session/apis/open_group_api/sogsv3/sogsV3MutationCache.ts

Also improved log message details for SOGS cache.

React Popup Text wrapping

---

stylesheets/_modules.scss

fix: fix rendering of link preview when no images are found

---

stylesheets/_session_conversation.scss
ts/components/SessionPasswordPrompt.tsx
ts/components/conversation/message/message-item/GenericReadableMessage.tsx
ts/mains/main_node.ts
ts/test/types/Settings_test.ts
ts/util/notifications.ts

also fix about/debug window first showing

fix: selected message box shadow and hide button while loading DB

---

package.json
stylesheets/_modules.scss
stylesheets/_session_theme.scss
yarn.lock

Fix padding jumbo emojis & add concurrently

---

_locales/en/messages.json
ts/components/SessionWrapperModal.tsx
ts/components/basic/SessionToast.tsx
ts/components/dialog/EditProfileDialog.tsx
ts/components/leftpane/ActionsPanel.tsx
ts/components/leftpane/LeftPane.tsx
ts/components/registration/RegistrationStages.tsx
ts/components/registration/RegistrationUserDetails.tsx
ts/components/registration/SignInTab.tsx
ts/components/registration/SignUpTab.tsx
ts/session/constants.ts
ts/session/utils/String.ts
ts/types/LocalizerKeys.ts

fix: displayName allowed length based on bytes rather than char

---

ts/components/icon/SessionNotificationCount.tsx
ts/components/leftpane/ActionsPanel.tsx
ts/state/selectors/conversations.ts

merging #2506 into this one
https://user-images.githubusercontent.com/1544279/197098449-10a400b0-95cc-4735-b280-2921925871a7.mp4

fix: padding with only one digit in unread notification count

---

ts/components/leftpane/conversation-list-item/HeaderItem.tsx
ts/session/constants.ts

Fixes https://github.com/oxen-io/session-desktop/issues/2613

fix: unreadcount messages maximum of 9999+

---

stylesheets/_session.scss
stylesheets/_session_theme.scss
ts/components/conversation/message/message-content/MessageAvatar.tsx
ts/components/conversation/message/message-content/MessageContentWithStatus.tsx
ts/components/conversation/message/message-content/MessageReactions.tsx
ts/components/conversation/message/message-item/GenericReadableMessage.tsx
ts/components/dialog/ReactListModal.tsx
ts/state/selectors/conversations.ts

fix: avatar at bottom, reacts with margin

---

CONTRIBUTING.md
INTERNALBUILDS.md
README.md
_locales/en/messages.json

Update Building and Contributing docs, please add any corrections to this, this one is important for first time contributors

Update Contributor/Building docs

---

ts/components/dialog/EditProfileDialog.tsx
ts/components/dialog/SessionSeedModal.tsx
ts/components/leftpane/conversation-list-item/HeaderItem.tsx
ts/util/saveQRCode.ts

Fixes https://github.com/oxen-io/session-desktop/issues/2586, https://github.com/oxen-io/session-desktop/issues/1860
Tested on ubuntu

feat: added ability to save qr codes on click

---

.github/workflows/build-binaries.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

chore: update github actions ubuntu to 20.04

---

README.md

Last one was quite out of date

Update Session desktop readme image

---

stylesheets/_session_signin.scss
ts/components/SessionMainPanel.tsx
ts/components/basic/Flex.tsx
ts/components/basic/SessionInput.tsx
ts/components/conversation/SessionConversation.tsx
ts/components/conversation/SessionEmojiPanel.tsx
ts/components/conversation/composition/CompositionBox.tsx
ts/components/conversation/composition/EmojiQuickResult.tsx
ts/components/conversation/composition/UserMentions.tsx
ts/components/menu/Menu.tsx
ts/mains/main_node.ts
ts/mains/main_renderer.tsx
ts/state/smart/SessionConversation.ts
ts/util/i18n.ts

taken https://github.com/oxen-io/session-desktop/pull/2796 from just updated with latest unstable

Feature/ses 379/composition rtl support

---

ts/components/leftpane/overlay/OverlayMessage.tsx

fix: trim pubkey before starting a convo with them

---

ts/node/sql.ts
ts/session/utils/libsession/libsession_utils_contacts.ts
ts/test/session/unit/libsession_wrapper/libsession_wrapper_contacts_test.ts

fix: do not try to store contacts not matching pubkey regex in wrapper

---

ts/interactions/conversations/unsendingInteractions.ts

so we dont need options in the delete modal

SES-1434 fix: note to self convos cannot delete for everyone

---

ts/components/conversation/message/message-item/GenericReadableMessage.tsx

highlighting should only happen when a message is right clicked

SES-1441 fix: if we are in multiselect mode dont highlight the message

---

CONTRIBUTING.md

Add install instructions for fedora and related linux distros.

Add alternative linux/fedora install instructions to CONTRIBUTING.md

---

ts/components/basic/SessionRadio.tsx

Added a relative style to radio buttons to give its absolute label a reference point. This fixes the modal list radio button issue

Fix: add relative style to radio button

---

ts/components/dialog/UpdateGroupNameDialog.tsx

the constantMAX_GROUP_NAME_LENGTH is used

fix: group name limited to 30 chars

---

ts/components/leftpane/ActionsPanel.tsx
ts/hooks/useFetchLatestReleaseFromFileServer.ts
ts/session/fetch_latest_release/index.ts
ts/test/test-utils/utils/pubkey.ts
yarn.lock

once we've already fetched the latest release:
this but with 30minutes instead of 5:

feat: hit only once every 30mins the fs for release

---

ts/hooks/useIconToImageURL.tsx

Need to increase the wait time for mounting the qr code via react

Fix loading the Recovery Password QR Code on macOS with rosetta

---

ts/components/dialog/OpenUrlModal.tsx

Fixes https://github.com/oxen-io/session-desktop/issues/3230

Fix copy url button in open url modal
